### ISSUE TITLE
Search should ignore case

### ISSUE THREAD

**Issue by agalanin** [codinguser/gnucash-android#120]
Search in account list should ignore case.

Steps to reproduce:
1. create account "Транспорт"
2. try to search "трансп"
3. try to search "Трансп"

Expected results:
1. ok
2. Search result contain "Транспорт"
3. Search result contain "Транспорт"

Actual results:
1. ok
2. Empty search result
3. Search result contain "Транспорт"

**Comment by diogocp** [comment]
I followed the steps above on Android 6.0.1 and failed to reproduce the issue.

It looks like it was fixed in Android 5.0. See https://issuetracker.google.com/36918562#comment11.

**Comment by agalanin** [comment]
Works on Android 6.
