### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by Alvinator** [codinguser/gnucash-android#147]
Would be great to sync to the desktop app, I know everyone wants this in the back of their mind but I didn't see any actual new feature requests for it, so now there is one :)

...especially if we could save it to Google Drive, then it can sync across all devices like desktop computers, any android phone or tablet.... but it would need to be able to store a local copy just in case of network outage, and it would need to be able to determine how to update everything because some tx may be added to the desktop AND some to the phone before a sync occurs, don't want to lose both so you would need to be able to combine them somehow.

Thanks!!!  Its a great app already, I really appreciate it :)

**Comment by marcelkoeberl** [comment]
Would love to have live-data in GnuCash Android without having my data on Dropbox or G-Drive...

GnuCash has the ability to store data in databases. So in the first step... how about adding a new resource beneath G-Drive and DropBox called "Site-Local". It contacts via WiFi to a service that runs on your GnuCah-Machine. The service is more or less simple and only a Gateway/Connector for the Databasedriver.
All Cash-Data available in your private cloud! And no more Syncing (or overwriting) with files.

Already thought about such a feature?

**Comment by codinguser** [comment]
@marcelkoeberl Thanks for the feedback. We have given quite some thought to sync options.
What you describe needs extra parts not just for the app, but also on the desktop.  
Sorry, but we are not considering such a feature at this time.

**Comment by psamim** [comment]
Another option would be to share the underlying database file between desktop and Android version.

I mean let the Android app use/read/write to a XML or SQLite file and one can use Dropbox/Syncthing to sync and have this same database also on desktop so that Gnucash on desktop can use the same file.
