### ISSUE TITLE
Enhancement:  Change Default Currency for sub-accounts when Root account is changed

### ISSUE THREAD

**Issue by mnsanghvi** [codinguser/gnucash-android#168]
Currently if I change the Default Currency for a Root Account (Expenses), it does not apply to the sub-accounts.  There should be an option to apply this to sub-accounts.

**Comment by codinguser** [comment]
I'm not sure if this would be appropriate to do, esp given support for multi-currency transactions. 
I might have an expense account for when I'm abroad and I wouldn't want to just modify the currencies in bulk.
