### ISSUE TITLE
Import two different books

### ISSUE THREAD

**Issue by fefe982** [codinguser/gnucash-android#189]
We I'm playing with import function, I found that when I import two different book into the App, only accounts from the 1st one is shown on the main Accounts view. However, all accounts can be found from the accounts selection drop-down list. Also, a lot of accounts with the same name show up in the drop-down list. It is hard to tell which is which.

I didn't check the code yet, but I guess it has something to do with the two ROOT accounts from the two different book. Only one of the ROOT account (the 1st) is found and used to create the main Accounts view.

This let me think, should we allow importing two different book? If we allow it, how to merge them?

My idea is to forbid such importing, to make things simple and clear. Importing is only allowed when:
1. The accounts tree in the App is empty.
2. The ROOT account in the App has the same GUID with the imported ROOT account

If the condition is not met, all accounts (and transaction) would be cleared first (with user warned) and then import the new book.

**Comment by codinguser** [comment]
So we agree on import being done with the conditions you mentioned in your original post. 
@fefe982 could you implement this?

**Comment by fefe982** [comment]
Sure.

**Comment by fefe982** [comment]
When implementing this, I just thought of a simpler plan.
What about the content of DB is ALWAYS cleared before the import? I cannot quite think of when a merge should be useful, but a merge can cause problems.

For example:
1) User imported from GnuCash
2) User added some transactions in GnuCash android
3) New transactions are exported and imported in GnuCash
4) User re-import from GnuCash (merge will happen here)

This will result in duplicate transactions, as the GUID generated by Gnucash android and Gnucash cash desktop would be different for the transactions created in Gnucash android.

I also want to find a way to put clearing the DB and addition of new transactions in a single DB transaction when importing, to prevent data loss.

**Comment by codinguser** [comment]
I thought of that too, and it makes sense to always clear the database before import. We will of course always make a backup just in case. So if you can put all that in one database transaction, then go for it. 

I also plan to add automatic scheduled exporting before the 1.6.x release (see the Trello board). 

Btw, can you see if the desktop can open our backup (.gnca) files? Last I tried it crashed, but haven't tried again in a while.

**Comment by fefe982** [comment]
I haven't tried using the desktop to open our backups, but I don't think that will work. A lot of things are different. Such as ROOT account, different GUID schemes (cny-xxxxxx for account GUID), extra XML element (exported, and others), etc.

**Comment by fefe982** [comment]
Updated the PR to delete before import. Be sure to WARN the user about the possible data loss, when RESTORING backups and IMPORTING.
