### ISSUE TITLE
word-wrap on +/- button (german version)

### ISSUE THREAD

**Issue by nikopp** [codinguser/gnucash-android#203]
Since the introduction of the split transaction, the button +/- button is not wide enough to display the German word Einnahme.

![screenshot_2014-09-10-08-28-51](https://cloud.githubusercontent.com/assets/186798/4213358/05ee3a22-38b4-11e4-8b05-829eb2be4d0a.png)

**Comment by nikopp** [comment]
This bug is not fixed in 1.5.5.

So either b636b28 is not contained in 1.5.5 (although it says so) or the fix does not work.

**Comment by codinguser** [comment]
Fixed in v2.0.0
