### ISSUE TITLE
Crash when exporting transactions on 1.4.3

### ISSUE THREAD

**Issue by nodje** [codinguser/gnucash-android#223]
Basically, the stacktrace is saying:

NullPointerException: println needs a message at android.util.Log.println_native(Native Method)
at android.util.Log.e(Log.java:231)
at org.gnucash.android.export.ExporterAsyncTask.doInBackground(ExportAsyncTask.java:113)
at org.gnucash.android.export.ExporterAsyncTask.doInBackground(ExportAsyncTask.java:48)

Sounds pretty straightforward looking at the trace but I wonder why nobody has reported the bug earlier. It's a totally blocking bug for anyone using this app with the Gnucash desktop.

Could it be my distribution? MI UI 5

**Comment by codinguser** [comment]
@nodje can this issue be closed?
Or are you still experiences issues on 1.5.5?

**Comment by nodje** [comment]
I've had to start form scratch and recreate all my accounts to get exports to work again. I guess I won't be able to reproduce this bug ever.
