### ISSUE TITLE
Set the date to export transactions from (set exporting period)

### ISSUE THREAD

**Issue by VasoVV** [codinguser/gnucash-android#226]
Occurrence:
Sometimes the application fails to export “last transactions” (gives zero-length QIF on output).

Consequences:
As the result there is only one way to get data to PC: export "All transactions" (it could be a long period!!) and mark many hundreds transactions as duplicates (during importing to PC app) to import one hundred of new one.

Solution:
It would be perfect to get possibility to set up the date to export from in Export dialog.

**Comment by codinguser** [comment]
Fixed in v2.0.2
