### ISSUE TITLE
Importing Transactions from Desktop

### ISSUE THREAD

**Issue by src-r-r** [codinguser/gnucash-android#233]
Perhaps I'm missing something here, but I'm having difficulty importing expenses from the desktop to the mobile app. I can import my accounts, no problem. I do the following:

In Gnu cash desktop
1. Go to File > Export > Export Accounts
2. Save to [device]/sdcard/accounts.gnucash

In the mobile app
1. Go to Settings > Accounts > Import GnuCash accounts
2. Pick the file that was just exported.

And the app is filled with accounts.

However, I don't see any option to import transactions. I import an entire `.gnucash` file (a copy of my desktop `.gnucash` file) but was unable to do so. I tried exporting all transactions to CSV and (as expected), that failed.

I was about to roll up my sleeves and solve this bug, but--browsing the issues--this does not seem to be an issue.

Is it just me?

**Comment by shackra** [comment]
Man, I just want to sync transactions on my desktop GNU Cash book with Android and vice versa. Importing the Qif file exported by Android to the Desktop works fine. However, I can't sync the other way without creating a new book on Android.

What am I doing wrong?

**Comment by souldessin** [comment]
I have to ask the same as @shackra. I edit on the desktop and on mobile. I want to be able to see the balances on both without having to enter extra or reopen my gnucash file and deal with duplicates.

**Comment by montao** [comment]
Yes it's works to import the .gnucash file in Android and the transactions appear

**Comment by egamboa** [comment]
I'm getting an error ![image](https://user-images.githubusercontent.com/2028005/157582260-e7925861-5a4f-462e-a481-0a3be0577e6d.png)

![image](https://user-images.githubusercontent.com/2028005/157582305-a4446290-2a9b-403e-8bef-985fe7f730fa.png)

This is a new book done in Mac a saved into Cloud documents, then I go in my iPhone and try to import my .gnucash an fails. Any clues?

**Comment by pietro14** [comment]
@egamboa, I had a similar problem, and if I remember correctly, I was able to solve it by disabling the 'Compress file' option on Gnucash desktop. So, try to go to 'Edit' -> 'Preferences' -> 'General' and disable the 'Compress file' option.

Hope it helps

![screenshot_2022-03-10_09-54-02](https://user-images.githubusercontent.com/41691318/157626057-6c31055f-fee9-4b6a-95e9-abeda9d4f303.png)
