### ISSUE TITLE
Cannot easily import accounts from Desktop using Google Drive

### ISSUE THREAD

**Issue by liamdennehy** [codinguser/gnucash-android#234]
Weird, weird result when trying to import an accounts export from (Windows) GnuCash 2.4.13 to GnuCash Android 1.4.3, CyanogenMod 11:
1. GnuCash Desktop 2.4.13: File, Export, Export Accounts
2. Select Google Drive synchronised folder
3. Name the file PersonalAccounts
---- Location has file PersonalAccounts.gnucash
---- Location also has a log file
4. Ensure Google Drive is synchronised on Android device
5. In Android GnuCash 1.4.3 (empty config), Settings, Accounts, Import GnuCash Accounts, Google Drive, My Drive, applicable folder...
---- PersonalAccounts.gnucash is grey and cannot be selected
---- log file(s) are not grey, but obviously fail

Selecting "Keep on this device" in Google Drive makes no difference.
Renaming to a different file extension (even .log) still shows the file greyed out
Selecting download ot device in Google Drive shows it does not appear in the local File Manager under Downloads folder

Workaround is to download a third-party file manager (e.g. Astro) to locate the file in Downloads folder. This is not seamless.

Is this expected behaviour for Drive? Sending QIF exports work the other way around, but more on that in another issue.

**Comment by codinguser** [comment]
Fixed in v2.0.0
