### ISSUE TITLE
Cursor position problem in amount field

### ISSUE THREAD

**Issue by LoneShooter** [codinguser/gnucash-android#241]
The cursor is always moved to the end of the field during transaction's amount editing.

Reproduction steps:

1. Create new transaction with amount e.g. 1,234.56 and save it

2. Open the transaction again and try to change or delete any cipher

Current behavior: The cursor is moved to the end of the number deleting ciphers in front of it while typing.

Expected behavior: The cursor stays in place while typing without replacing existing ciphers..

**Comment by searoso** [comment]
Guys, I have another problem: gnucash doesnt let to manipulate cursor in ANY field. So if I want to edit a description of a transaction I should retype it entirely. 

Is it a variation of this problem, or should I file a new bug?

This is most similar place I found for my issue.

**Comment by codinguser** [comment]
@searoso you mean this happens for you not just in the account field, but in all other text fields as well?

**Comment by searoso** [comment]
Yes, indeed.
13.02.2015 13:50 пользователь "Ngewi Fet" <notifications@github.com>
написал:
