### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by fefe982** [codinguser/gnucash-android#250]
Let's continue our dicussion in #247 here, as it is already unrelated with the original topic.

1. You're right the develop is ahead of master, but that also means that we cannot merge from develop to master unless we are ready for 1.6.0 or 2.0. bugfixes must be cherry picked from develop to master. I think merge is better than cherry-pick.

2. As develop is ahead of master, some edits can only be applied to develop, but not possible on master. It will be hard to test which commit should be cherry-picked to master with a branch from it.

3. Bugs on master should be tested on master, and so does the bug fixes.

So I'm suggesting project structure like this:

----master
      \----hotfix

----develop

Bugfix (pull requests) can be made on hotfix. bugfix/hotfix will be merged to both master and develop.

New feature and bugfixes for bugs introduced by new features will be on develop.

When hotfix is ready, it can be merged to master to get v1.5.4 , and a new bugfix branch should be branched from v1.5.4.

Like #248 and #249 , I started these bugfixes both from seeing #247. But as the new features on develop, master and develop branches behave differently. It will hard to get a fix on master if we work only on develop.

**Comment by codinguser** [comment]
hotfix/patches branch created and in use

**Comment by gabrielsimoes** [comment]
I think this information should be added to contribution part in readme
