### ISSUE TITLE
QIF export does not work

### ISSUE THREAD

**Issue by agalanin** [codinguser/gnucash-android#253]
Steps to reproduce:
1. Open the application.
2.1. Select Menu -> Export transactions.
2.2. Select "SD Card" destination, QIF export type, "export all" and deselect "delete after export".
2.3. Click "Export" to start export.
2.4. Wait for export finish (message "QIF file exported to ..." displayed).
2.5. Check export location
3.1. Repeat 2.1-2.5 for OFX export type

Expected results:
2.5. QIF file exists in the export location.
3.1. OFX file exists in the export location.

Actual results:
2.5. No QIF file found.
3.1. OFX file exists in the export location.

**Comment by agalanin** [comment]
This bug still present in 1.5.4.

**Comment by codinguser** [comment]
Do you have double entry disabled?

**Comment by agalanin** [comment]
Yes, double entry is disabled.

**Comment by agalanin** [comment]
Fixed in 1.5.5.
