### ISSUE TITLE
Can't edit transactions

### ISSUE THREAD

**Issue by relgames** [codinguser/gnucash-android#254]
Version 1.5.1
Can't edit any transactions: it just doesn't save my changes.
The only way is to delete a transaction and then create a new one.

**Comment by codinguser** [comment]
Is this still happening or has it been fixed in the latest version?

**Comment by relgames** [comment]
Can't validate in 1.5.3 - I just can't create any record at all because of this https://github.com/codinguser/gnucash-android/issues/277

**Comment by relgames** [comment]
Checked in 1.5.2 - the ussue is still there.

**Comment by relgames** [comment]
Installed latest develop branch - it is fixed, thank you!
