### ISSUE TITLE
Autocomplete problems

### ISSUE THREAD

**Issue by cliff-barry** [codinguser/gnucash-android#256]
(My experience with this bug relates to issue #254 but is perhaps separate.)

When I create an entry for a purchase, the autocomplete list shows up, per usual.  If I pick one of the suggestions, the previous amount associated with that suggestion populates the field (normal behavior).  Even if I change the value before saving the entry, the old value is retained.  Editing the entry later has the same result, the old transaction amount sticks.  Luckly I caught this before too many entries were affected.

I would like to be able to completely disable the autocomplete feature, or at least disable the automatic population of the transaction amount.  The majority of my transactions are not repetitive (different dollar amounts at the same stores, varying bills each month, etc), and it ends up creating a lot more work than it saves me time.

Thanks for your hard work on this project!

**Comment by codinguser** [comment]
This issue should be fixed, I don't remember exactly in what commit it was.
@cliff-barry are you still experiencing this issue, or can it be closed?

Also, in the upcoming version, autocomplete works only with explicitly-created transaction templates.

**Comment by cliff-barry** [comment]
I'm using the latest version on F-Droid, 1.5.1.  I still experience this
issue.

Cliff

**Comment by codinguser** [comment]
The latest version on FDroid is 1.5.5.
Could you please upgrade and let me know? Thanks

**Comment by cliff-barry** [comment]
Hmm, it hadn't shown the update within F-Droid itself (though it showed
other apps).  I've manually updated it to 1.5.5.  Give me a few days to
build up transactions in the new account and I will get back to you.

Thanks!
Cliff Barry

**Comment by codinguser** [comment]
:+1:
