### ISSUE TITLE
skip passcode input layout with SwipeBack

### ISSUE THREAD

**Issue by iptux** [codinguser/gnucash-android#257]
SwipeBack is a Xposed module that use swipe gesture to perform back operation
I'm have install both GnuCash and SwipeBack,
and found that the passcode input layout can be swiped and enter the main ui directly
I think it's a security issue

More about SwipeBack: http://repo.xposed.info/module/us.shandian.mod.swipeback

**Comment by codinguser** [comment]
@aint could you look into this?

**Comment by aint** [comment]
Check this [pull request](https://github.com/codinguser/gnucash-android/pull/280), please.

**Comment by codinguser** [comment]
@iptux can you confirm that this issue is fixed in the latest version (v1.5.4)?
Then I would close this issue

**Comment by iptux** [comment]
Not fixed in v1.5.4(from F-Droid).

**Comment by aint** [comment]
This is of course not working, because my fix __not included__ in in the latest version.
![screen shot 2015-02-17 at 2 37 09 pm](https://cloud.githubusercontent.com/assets/3179252/6228316/f6e5c748-b6b2-11e4-8b0e-e818e024144a.png)

**Comment by codinguser** [comment]
mea culpa... you are right!
It will come in a future release

**Comment by iptux** [comment]
Not fully fixed in v1.5.5(from F-Droid).

This time swipe the passcode don't show main ui, the app quit out. Passcode is required if app started again.
But if I'm fast enough, that is swipe the passcode IMMEDIATELY after passcode layout shows up, I have CHANCE to enter the main ui directly at app's next start.
So after repeating the "start app -> swipe out -> app quit" loop several times, I can enter the main ui without a passcode.
