### ISSUE TITLE
Crash after clear amount

### ISSUE THREAD

**Issue by johngray1965** [codinguser/gnucash-android#259]
E/AndroidRuntime(23349): java.lang.IndexOutOfBoundsException: charAt: 0 >= length 0
E/AndroidRuntime(23349): 	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:114)
E/AndroidRuntime(23349): 	at org.gnucash.android.ui.transaction.TransactionFormFragment$AmountTextWatcher.afterTextChanged(TransactionFormFragment.java:830)
E/AndroidRuntime(23349): 	at android.widget.TextView.sendAfterTextChanged(TextView.java:7435)
E/AndroidRuntime(23349): 	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9209)
E/AndroidRuntime(23349): 	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:970)
E/AndroidRuntime(23349): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:497)
E/AndroidRuntime(23349): 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
E/AndroidRuntime(23349): 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
E/AndroidRuntime(23349): 	at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:244)
E/AndroidRuntime(23349): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:382)
E/AndroidRuntime(23349): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
E/AndroidRuntime(23349): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(23349): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(23349): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime(23349): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23349): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23349): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(23349): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(23349): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by codinguser** [comment]
Does this still happen in the latest release?

**Comment by johngray1965** [comment]
Yes.  I recently did a "Clear Data" and it was working better, but I saw it again a little while later.

**Comment by bram85** [comment]
You should at least check that the string length is greater than zero before doing charAt(0).

https://github.com/codinguser/gnucash-android/blob/master/app/src/org/gnucash/android/ui/transaction/TransactionFormFragment.java#L865

**Comment by codinguser** [comment]
Yes, that is in the recent builds!
