### ISSUE TITLE
Crash when enabling and setting passcode permanently locks user out.

### ISSUE THREAD

**Issue by jordonbiondo** [codinguser/gnucash-android#263]
I installed from the play store on 4.4.2.

I can repeat the bug following these steps.

1. install app
2. open app, create accounts
3. go to settings -> passcode
4. enable passcode and set passcode
5. enter passcode once
6. enter passcode again
7. app reports crash, but takes me back to accounts page.
8. fully shutdown and relaunch app
9. asks for passcode
10. enter code I input earlier
11. does not accept passcode.

If I instead go back to settings after step 7 and try to set the passcode again, the same thing happens.

I am currently just not using a passcode and everything is working, but I would like to be able to use that feature.

**Comment by codinguser** [comment]
@jordonbiondo do you still experience this on latest versions?

**Comment by jordonbiondo** [comment]
Sorry I don't have an android device any more to test it.
