### ISSUE TITLE
Add support for TRADING accounts (currently crashes during import)

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#269]
I can't import accounts from the desktop version. It says something like "trading is not a constant"
![screenshot_2014-11-16-13-30-16](https://cloud.githubusercontent.com/assets/276699/5115428/3f45fcbe-7041-11e4-8a8c-8146d9c3b764.png)

**Comment by tiagosab** [comment]
Any news about this? It would be great!

**Comment by codinguser** [comment]
Sorry for the delays. Will try to get it out as soon as possible!

**Comment by codinguser** [comment]
Fixed in v1.5.2
