### ISSUE TITLE
sometimes the plus to add a transaction is missing

### ISSUE THREAD

**Issue by MaDill** [codinguser/gnucash-android#274]
the right + next to a account is some times missing. I open a account and on the actual showed display the + is shown in the screen. When I now scroll down/up these + disappear. I use the German version 1.5.1
This is when open the account:
![screenshot_2015-01-23-14-16-12](https://cloud.githubusercontent.com/assets/7298934/5875243/634d551a-a30b-11e4-8096-80f139fd989e.png)

This is after scrolling down/up
![screenshot_2015-01-23-14-16-23](https://cloud.githubusercontent.com/assets/7298934/5875244/635a9356-a30b-11e4-9097-b947eaf621ff.png)

**Comment by codinguser** [comment]
Thanks for reporting that!

**Comment by codinguser** [comment]
Fixed in v2.0.0
