### ISSUE TITLE
Confusing names in the list of currencies

### ISSUE THREAD

**Issue by MisterY** [codinguser/gnucash-android#278]
<s>Hi, I've noticed that the Bosnian Convertible Mark (BAM) is missing in the list of currencies. As the list of currencies is not editable, there is no way to use this currency.</s>

I've just noticed that some currencies have a country in the name but others don't. I've found Convertible Mark and Forint currencies. However, the naming is a bit confusing. Perhaps, adding the currency codes (+ sorting) would make things easier. Just a suggestion.

**Comment by codinguser** [comment]
Currencies are now sorted by country codes when creating an account.
