### ISSUE TITLE
Some transactions not exported to QIF

### ISSUE THREAD

**Issue by MisterY** [codinguser/gnucash-android#279]
When disabling "Activate Double Entry" option in settings, the transactions created thereafter will not be exported to QIF.
They are missing the transfer account (category) on entry but, more importantly, will not show up in QIF file at all.

**Comment by codinguser** [comment]
@fefe982 could you look into this?

**Comment by fefe982** [comment]
Sure.

**Comment by codinguser** [comment]
Fixed v1.5.5
