### ISSUE TITLE
QIF export does not delete transactions 

### ISSUE THREAD

**Issue by shaffenmeister** [codinguser/gnucash-android#281]
Observation:
* When exporting all transactions with the option "delete after export", transaction only are deleted when using destination "SD Card"
* When using destination "Send to", the .qif is exported successfully, but transactions are not deleted
* Destinations tested: Seafile, Android standard, EMail client, GMail .

Expected behaviour:
* Files should be deleted irrespective of the export destination upon successful export.

Reproducibility:
1. Open the application.
1.1. In Setup > Common ("Allgemein") > deselect "Delete exported transactions".
2.1. Select Menu -> Export transactions.
2.2. Select "Send to" destination, QIF export type, "export all" and select "delete after export".
2.3. Click "Export" to start export.
2.4. Wait for export finish (gnucash returns to screen "Enter passcode").
3.1. Enter passcode
3.2. Open screen "Accounts"
3.3. Repeat from 1.1., select "Delete exported transactions".

Expected results:
3.2. All accounts should display e.g. 0,00 €.
3.3. All accounts should display e.g. 0,00 €.

Actual results:
3.2. All transactions still present, accounts show their previous amount.
3.3. All transactions still present, accounts show their previous amount.

Android 4.3
Gnucash Android 1.5.3

**Comment by rivaldi8** [comment]
This seems related to #285.

**Comment by codinguser** [comment]
Fixed in 6d91b5f8c047124c8247af87e1b62a7c24ad59a5
Transactions will always be deleted after export and no confirmation dialog will be shown!
