### ISSUE TITLE
Delete confirmation blocked by passcode screen

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#285]
From email bug report: 
"I have a passcode setup and it drops me back out to re-enter the passcode after I've exported transactions, then the delete transactions confirmation has disappeared. I've just tried turning off the passcode and the confirmation box is still there.
I would say this is a bug as it ought to work with passcode enabled, I would suggest sensible behaviour would be to not kick you out to re-enter the passcode after exporting transactions."

**Comment by codinguser** [comment]
On the other hand, those delete confirmation dialogs may probably go away once backup and restore options in the UI have been improved upon, (planned for a future release). So in the long run, it will not be relevant for the purposes of confirming delete after export.

**Comment by aint** [comment]
Not completely clear report, but it seems that I found the source of trouble. When the user try to export transactions to _SD Card_ all works as well. But when _"Share file"_ option is selected then starts an [intent chooser](https://github.com/codinguser/gnucash-android/blob/develop/app/src/main/java/org/gnucash/android/export/ExporterAsyncTask.java#L255). In this case displaying the dialog-as-an-Activity will cause pausing _AccountsActivity_ what previously was there. After selected share destination calling the _AccountsActivity_'s onResume() method. And if pause is greater than 5 seconds the passcode screen appears. So, nothing to do with delete confirmation dialogs.
[Here's the fix](https://github.com/codinguser/gnucash-android/pull/286). Not elegant but works.

**Comment by codinguser** [comment]
Yes, the issue with delete confirmation dialog after export is moot, because those will go away soon.
@aint Do you the fix is still necessary then? 
Because after exporting, and if it took long in another program, I see no problem with requiring the user to enter the passcode again.

**Comment by aint** [comment]
IMHO it's annoying to enter a password some additional times.

**Comment by codinguser** [comment]
Fixed in 6d91b5f8c047124c8247af87e1b62a7c24ad59a5
Transactions will always be deleted and no dialog will be shown!
