### ISSUE TITLE
Passcode screen can be skipped

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#289]
From user feedback: 

I found a bug in 1.5.5(Play Store).

What?
Skip Passcode-Screen

Reproduce?
Open GnuCash. Passcode screen comes up. Press Android-TaskList-Button. Select GnuCash. Passcode-Screen is skiped.

I use Lollipop(CM12)

**Comment by codinguser** [comment]
I can confirm this bug on Lollipop
@aint could you look into this? thanks

**Comment by aint** [comment]
Sure.

**Comment by codinguser** [comment]
Fixed in 896329da8306c13ec810c5678a4b3377c8aee215
