### ISSUE TITLE
drawer_list_item.xml uses theme values only available from API level 11 onwards

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#291]
The layout file drawer_list_item.xml uses theme attributes only available from API level 11 onwards, although AndroidManifests declares a minSdkVersion of 9.

This causes GnuCash to crash when starting on my HTC Wildfire (API level 10 - Android 2.3.5).

**Comment by codinguser** [comment]
Thanks for picking up on that. i'll look if the fix #291 looks the same on API level 11 and up
