### ISSUE TITLE
Account balance should show real-time balance (and ignore future transactions)

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#300]
Some transactions may be saved with a timestamp in the future. These should be ignored when computing the account balance. The transaction timestamp is set by the user.

There are always the created_at and modified_at timestamps in the db (develop) which we can lookup for other purposes. 

@fefe982 could you look into this? Thanks

**Comment by fefe982** [comment]
OK. No problem.

**Comment by codinguser** [comment]
Fixed in f60639927177136073a074a609e9ab06ca9e3258
