### ISSUE TITLE
Sort autocomplete suggestions from latest (in time) to oldest

### ISSUE THREAD

**Issue by monoman** [codinguser/gnucash-android#307]
Inflation is back here in Brazil, and is common in many places, so prices (and thus transaction amounts) go up but rarely go back down, having to scroll down the suggestion list to get the right amount to auto-complete is cumbersome.

**Comment by codinguser** [comment]
In the next version, explicit saving of transaction templates is introduced and auto-complete only works with those templates (and not all transactions in the database). 
The code for this feature is already in the develop branch.

**Comment by monoman** [comment]
:100:

**Comment by codinguser** [comment]
Fixed in 487bc1287144d5dbbc072a4f2aa29b2c2f1eee8a
