### ISSUE TITLE
Allow for editing amount values in the middle positions more easily

### ISSUE THREAD

**Issue by monoman** [codinguser/gnucash-android#308]
I put the cursor in the middle to delete a char and write another, but the cursor gets back to the end making me curse. This forces me to delete lots of chars and reenter them, wasting my time.

470,00 to 480,00 today I need to do <= <= <= <= 8 0 0 0
I would like to do:
470,00 &lt;tap just after 7&gt; <= 8

It could be a setting I opt in, so that users that like the current behavior keep it that way...

**Comment by codinguser** [comment]
You cannot delete from the middle. Only from the end. This is by design.
This has to do with the different formatting of currency for different locales.

**Comment by monoman** [comment]
Then a clear-all micro-button would help immensely

**Comment by codinguser** [comment]
Nice idea :+1:
