### ISSUE TITLE
Importing old backups (with non-balanced splits) fails 

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#318]
Importing old backups which do not have balanced splits fails due to a "FOREIGN key constraint fails" when bulk adding splits. This I think is the the split account uid foreign constraint.
Auto-balancing takes place during the import process (and that includes creating the imbalance account). So db has to be cleared before importing starts. I've made the adjustments in the develop branch, but still the import fails.
@fefe982 could you look into it? I could send you some old files if you don't have any.

**Comment by fefe982** [comment]
Sure. I've already know the reason, and patch may come up with some other enhancements (if possible) and bug fixes on the XML import procedure.

**Comment by codinguser** [comment]
:+1:
