### ISSUE TITLE
"Negative" account in pie chart

### ISSUE THREAD

**Issue by fefe982** [codinguser/gnucash-android#320]
Haven't read the code, but:

When pie chart is shown, the absolute value is used. It will be an error if the sign of some accounts are different from others.

In my account tree, under INCOME, one account only has splits whose type if different from all other accounts under INCOME. In pie chart, its absolute value is shown together with all other accounts, taking a (big) portion of the pie chart.

E.g, under INOCOME
subAccount1 : -10000
subAccount2 :  20000
subAccount3 :  30000

subAccount1 now takes 1/6 of the pie chart.

**Comment by codinguser** [comment]
@aint I guess this falls in your domain ;)

**Comment by aint** [comment]
Hi all, I'm sorry for the delay in replying, will answer all emails today.

So what is right solution for this issue? Should we just ignore all negative values like GnuCash Desktop?

BTW, what about a line chart in the same situation?

**Comment by aint** [comment]
Currently, MPAndroidChart doesn't have proper support for negative values, so I think the best approach is to add ability to user to select: ignore negatives or use absolute values.

**Comment by codinguser** [comment]
@aint is this issue fixed? 

I think we updated the version of the library in the app right?
http://stackoverflow.com/questions/26626517/i-cannot-draw-negative-y-values-and-positive-y-values-in-one-barchart-using-mpan

**Comment by aint** [comment]
I'm so sorry. I just forgot about it.

**Comment by codinguser** [comment]
@aint It seems the barchart still shows just absolute values and the axis always starts at zero.
Do we not need the method `setStartAtZero(false)`?

Or maybe I'm missing something in how to make entries to visualize negative values in the barchart

**Comment by aint** [comment]
The bar chart should displays negative values by default. ```setStartAtZero(false)``` already used
https://github.com/codinguser/gnucash-android/blob/develop/app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java#L151


![2015-11-06 19 46 10](https://cloud.githubusercontent.com/assets/3179252/11004279/fca5f0aa-84bf-11e5-8cfb-e9034ae7d92a.png)
![zkxgwzpwkzdfuluvk8o8vm5sazwjapeyrjh6qlei1rw](https://cloud.githubusercontent.com/assets/3179252/11004282/00bd0b60-84c0-11e5-8d3c-449849b98f4e.png)

**Comment by codinguser** [comment]
Oh alright. My bad, I missed that.
Thanks.
