### ISSUE TITLE
Multicurrency in charts

### ISSUE THREAD

**Issue by fefe982** [codinguser/gnucash-android#321]
I have multiple currencies in my book. In line chart and bar chart, only the absolute value is taken into account, making the whole graph less useful. The income and expense in JPY has great value, making my income in other periods (which are in other currencies) shown very small, and not very clear.

Without  exchange rate, can I choose which currency to be shown on certain chart?

**Comment by aint** [comment]
I have this in plan, it's gonna take a while.

**Comment by codinguser** [comment]
Fixed in a59632ed587e92889bb00e68b3c987950dddb682
