### ISSUE TITLE
amount input problem with Swype

### ISSUE THREAD

**Issue by PhilippSchlesinger** [codinguser/gnucash-android#33]
When trying to enter an amount and type '1', it repeats printing '1' around 20 times and afterwards it repeats printing '0' infinitely so I get a very big amount ;-)

This is on Motorola Defy+ MB526 Android 2.3.4  with Swype 3.23.89

**Comment by codinguser** [comment]
Merged the patch. Can someone confirm that this issue is fixed in the latest release?
