### ISSUE TITLE
Can't Restore Backup

### ISSUE THREAD

**Issue by pjridge** [codinguser/gnucash-android#355]
I did a backup and the next time i opened gnucash, all of my transactions were gone and all that is showing is the original acconts chart.  I am trying to restore the  backup but keep getting the message,  "an error occurred while importing the gnucash accounts.  Multiple root accounts exist in book".

How to remedy?

Peter

**Comment by codinguser** [comment]
Thanks for the report. We're looking into this 
cc @fefe982

**Comment by pjridge** [comment]
Thanks.

Could I send you the file?

It may be of interest that the file was one I built from scratch rather than taking the standard chart and adding accounts. I started with a simple chart of about five expenses, two credit cards and two banks (which was all I would need for my three weeks holiday).Then I added some placeholder accounts and attached the original accounts to them (had some time on my hands and wanted to play with the system to see how it all worked). Ended up with a three level hierarchy. Then I thought I should do a backup so as not to lose it all. Don't know what I did to make it all disappear.

Of interest, I'm off on holidays again next week, this time for ten weeks and did want to use the app on the way. Wonder if I start with the standard chart and fill in my own accounts under that will I have more success. I'll certainly try backing up early in the process, so If it does happen again, I won't lose too  much.

Peter

**Comment by codinguser** [comment]
Yes, it would be helpful if you could send me the file.
You can send it to gnucash.org@gmail.com
Thanks!

**Comment by fefe982** [comment]
@codinguser Have you got the file? Would you send the file to me?

Sorry if you have already forwarded me the file, I may have missed some emails when I went to attend a conference.

**Comment by codinguser** [comment]
@fefe982 no, I don't have it yet.
@pjridge if you could send us the file that would be great!

**Comment by pjridge** [comment]
file attached. thanks
  ----- Original Message -----

**Comment by pjridge** [comment]
----- Original Message -----

**Comment by codinguser** [comment]
@pjridge it seems you cannot attach files (only pics) on GitHub. Please try sending via email to gnucash.org@gmail.com

**Comment by codinguser** [comment]
@pjridge do you still experience this issue?

**Comment by pjridge** [comment]
Hi, Ngewi. Funny thing is that, although I was using GNUCash while I was travelling 4 Aug to 10 Oct, I wasn't game to back up in case I had the same problem as last time (ie June). I seem to remember seeing some sort of auto backups anyway.

I just tried a backup and restore just now and it worked fine. I must say, however, that this time I was using a stock standard file structure, not a structure that I had mucked around with as much as I did when the problem arose last time.

Give me a few days. I will do some adjustments to the structure, then back up and see if it will restore.

Peter

**Comment by pjridge** [comment]
After a few more tries with a couple of files, it all seems to work fine. Thanks.

**Comment by maksue** [comment]
i have the same problem... anyone can help me to recover my data?

**Comment by codinguser** [comment]
@maksue sorry about this issue. We are still trying to identify what causes it so as to fix it. 
If you like, you can send me your file to gnucash.org@gmail.com and I can try to modify it for you so that it can be restored.

**Comment by maksue** [comment]
Hi Ngewi....

Thank you for your respond. Herewith the backup file.... really appriacte
if you can get back my data.

Thanks again.

**Comment by codinguser** [comment]
@maksue it seems you forgot to send the file. 
Send it to the email I gave, instead of using the reply button which will instead post a new comment.

**Comment by maksue** [comment]
Sorry... already resend the email :+1:

**Comment by codinguser** [comment]
The file is in OFX format. GnuCash Android can only restore backups from
XML.
You can try to import the OFX file in GnuCash desktop, and then save again
as .gnucash file (which is in XML).
Then you can import the .gnucash file into GnuCash Android.
