### ISSUE TITLE
"Save" and "Cancel" transaction buttons are disappeared from the menu bar

### ISSUE THREAD

**Issue by agalanin** [codinguser/gnucash-android#358]
Buttons for saving and cancelling transaction are disappeared from the menu bar in transaction editor since version 1.6.0. Now I need to open menu and click buttons there, but this is less comfortable. Please, re-add buttons to the menu bar.

**Comment by codinguser** [comment]
What Android version are you using?
Does this happen in v1.6.2 as well?

**Comment by agalanin** [comment]
Android 2.3.6.
Yes, this problem is present in v 1.6.2.

**Comment by codinguser** [comment]
This should be fixed in v2.0.0

**Comment by agalanin** [comment]
Yes, fixed in 2.0.0
