### ISSUE TITLE
"Done" button for date editor does not fit into the screen

### ISSUE THREAD

**Issue by agalanin** [codinguser/gnucash-android#359]
My phone has screen with size 180x192. When I open date editor in portrait screen orientation "Done" button is not visible, so I can't edit transaction date.

**Comment by codinguser** [comment]
Is this issue fixed for you in v2.0.0

**Comment by agalanin** [comment]
no, still present

**Comment by codinguser** [comment]
ok, will be fixed in v2.1.0

**Comment by codinguser** [comment]
v2.1.0 is now in beta
