### ISSUE TITLE
Crash when creating backup, can't export transactions in XML

### ISSUE THREAD

**Issue by aethertap** [codinguser/gnucash-android#360]
I'm unable to either backup or export my gnucash data. When attempting to export, I get an error message and the export fails after a few bytes have been written. When I try to do a backup, gnucash crashes. I don't know if the crash is caused by the same error as the export failure, but it seems likely.

The error message I see when trying to export transactions flashes past very quickly, but I believe this is the whole thing:

    Error exporting XML file
    Failed to generate GnuCash XML-Attempt to invoke virtual method 'java.lang.String.org.gnucash.android.model.Account.getName()' on a null object reference

**Comment by fefe982** [comment]
The getName() in export appears in export templates and export scheduled transactions.

I don't know why we got an empty account yet.

**Comment by codinguser** [comment]
@aethertap are you still having this issue?

**Comment by aethertap** [comment]
No, it seems to be working now.
