### ISSUE TITLE
Unable to Import XML file if it contains a budget

### ISSUE THREAD

**Issue by c-janousek** [codinguser/gnucash-android#361]
If I attempt to import a GnuCash XML file that has a budget with in it, the operation fails. The error message flashes to briefly to for me to record it fully but it returns something like "An error occurred while importing GnuCash accounts. Attempts to invoke virtual method void org.gnucash.android.model.Scheduled.action.set.period (org.gnucash.model.Period.type) on a null object reference"

If I import the same XML file without the budget included the operation succeeds

**Comment by codinguser** [comment]
What version are you using? Are you on the latest version, v1.6.4?

**Comment by c-janousek** [comment]
1.6.3. Looks like 1.6.4 hasn't been pushed out to f-droid yet. Will update once 1.6.4 is available

**Comment by codinguser** [comment]
Ok. I think v1.6.4 fixed the issue.
