### ISSUE TITLE
Scheduled transactions not working

### ISSUE THREAD

**Issue by xavrin** [codinguser/gnucash-android#374]
I've scheduled a transaction but it's not working.
No transactions are created.

**Comment by elmerehbi** [comment]
@xavrin it works for me. I have several.

@codinguser I noticed this some time ago.I think every time the app is updated the scheduled transactions stop working.

**Comment by codinguser** [comment]
@elmerehbi @xavrin we're working on improving scheduled transactions

**Comment by codinguser** [comment]
@xavrin v2.1.0 which is currently in beta should significantly improve the reliability of scheduled transactions. 
Final release coming in the next few weeks
