### ISSUE TITLE
the same database for desktop and android

### ISSUE THREAD

**Issue by DavidWind** [codinguser/gnucash-android#375]
Hi all,

Obviously it should be discussed somewhere before but I was unable to find it :-/

Suggestion: make android app able to use the same data file as desktop version. This would let to live without exports/imports, just synchronization of data file (e.g. using cloud).

**Comment by codinguser** [comment]
Yeah, you're right, this has been discussed a lot previously in several issues here on GitHub.
Unfortunately, it's not going to be happening any time soon due to feature incompatibility between the apps, and also to avoid data corruption

**Comment by singpolyma** [comment]
This is almost possible now, if you do an XML export and overwrite the gnucash file you imported, you basically get this. Just need an option to save to a particular file instead of also to an app-specific directory.

**Comment by codinguser** [comment]
Merge into #567 
Issue will be tracked there

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:26742)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7866-nacho=ownyourbits.com@sgmail.github.com>)
	id 1cVaJD-0015aH-IN
	for nacho@ownyourbits.com; Mon, 23 Jan 2017 03:49:03 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vlEPM/Vwd8zz4kzdgj5rI9riOf4=; b=QMDjL1WwZrH5V8dt
	hxhyVISSm+X2sNLvyw1hFO/aQP+vMWITLwuJgnwDvXr/oTQtt1OgfWS2e/C4mHDG
	3CIrTdjduipSdEsgx7w25l121joRVFv3rqj8s1Lrppy+qc942Z1GbKcKY0gHIaC2
	JNpXl3pTE2bHcrUk8AIiQHzLuBw=
Received: by filter0942p1mdw1.sendgrid.net with SMTP id filter0942p1mdw1-12088-5885C353-4E
        2017-01-23 08:48:19.67059267 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 6QFkDq-fTpmMcWZGQZfmXQ
	for <nacho@ownyourbits.com>; Mon, 23 Jan 2017 08:48:19.731 +0000 (UTC)
Date: Mon, 23 Jan 2017 00:48:19 -0800
