### ISSUE TITLE
Export deleted transactions to desktop

### ISSUE THREAD

**Issue by andrewculda** [codinguser/gnucash-android#387]
Hi!

I've recently started using the mobile Gnucash companion.
I see that all new transactions can be exported to GoogleDrive and the imported on the desktop.
However, I've noticed that if I delete transactions on the mobile app, the actions cannot be exported (included in the qif files) to be later imported in the desktop application. Which means that I cannot sync my "delete" actions with the desktop app, only new entries.

Is there a way to change this?

**Comment by codinguser** [comment]
No, sorry. You cannot sync delete actions. You can only export newly
created transactions.
