### ISSUE TITLE
V 2.0 crashes on my motox

### ISSUE THREAD

**Issue by boydkelly** [codinguser/gnucash-android#388]
Hi,
Installed the 2.0 apk from gnucash dev list while bored waiting in an airport.  I can no longer start gnucash-android.  Also was negligent enough not to have done a backup/export.  Any suggestions as to the best way to revert/recover data?  Will simple uninstall remove the data?  I can't see where this is located.  Thanks!

**Comment by codinguser** [comment]
No, do not uninstall!
Does the app not start at all (crash on start), or starts before crashing?
Send me a mail at gnucash.org@gmail.com and I can send you a build to test
