### ISSUE TITLE
Changing the transfer account of the split with the total amount set it to zero

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#416]
If a transaction is edited and the transfer account of the split entry with the positive amount is changed, the amount of the transaction is set to zero.

Steps to reproduce:
1. Create a new transaction in *Expenses:Education*.
2. Enter a description and an amount.
3. Save the transaction.
4. Edit again the same transaction.
5. Open the split editor.
6. There will be two entries, one with negative amount and the other with a positive amount. For example -100 and 100.
7. Change the transfer account of the entry with the positive amount (100) to *Expenses:Books*.
8. Save the changes.
9. The split editor closes and the transaction account appears with 0 as its amount.

Some observations:
- The transactions disappears from *Expenses:Education* and appears in *Expenses:Book*, just as expected.
- The amount of the transaction and its splits are set to 0.
- If after step 2, the split editor is opened instead, there's only the split with the positive amount and its transfer account can't be changed (the combo box is disabled).

**Comment by codinguser** [comment]
Thanks for the comprehensive report :+1:
