### ISSUE TITLE
Danish translation is in Norwegian

### ISSUE THREAD

**Issue by Freso** [codinguser/gnucash-android#418]
I don't think there's a single string in Danish in [values-da-rDK/strings.xml](https://github.com/codinguser/gnucash-android/blob/develop/app/src/main/res/values-da-rDK/strings.xml); from what I can tell the entire file is in Norwegian. (No idea whether it's Bokmål or Nynorsk though.) Is there a reason for this? It was added in 0d3e0c7c0c8b643be2e374469041c135cb215834 which doesn't give a whole lot of context in the commit message, other than mentioning CrowdIn (which isn't mentioned in the [referenced](https://github.com/codinguser/gnucash-android/blob/master/README.md#contributing) [help-to-translate blog post](http://www.codinguser.com/2012/09/gnucash-for-android-beta-2-lost-in-translation/) - is that what we're supposed to be using if we want to help with translations?).

**Comment by codinguser** [comment]
I think I uploaded translations in error. 
I will revert them to English

**Comment by Freso** [comment]
But is CrowdIn what I'm supposed to use if I do want to help contribute Danish translations?

**Comment by codinguser** [comment]
Yes!
