### ISSUE TITLE
Bug: Sums set to zero when renaming account

### ISSUE THREAD

**Issue by bugmenot2** [codinguser/gnucash-android#436]
Applies to all amounts of all children accounts of the account renamed. OUCH!

**Comment by fefe982** [comment]
Confirmed on the lasted release v2.0.3.

I also found the transaction disappeared.

**Comment by codinguser** [comment]
Fixed in v2.0.4

**Comment by bugmenot2** [comment]
please push this to f-droid. it's still 1.6 there!
