### ISSUE TITLE
Order of items in QIF export

### ISSUE THREAD

**Issue by behrmann** [codinguser/gnucash-android#461]
When importing a QIF in Gnucash 2.6.9 that was generated by the app the transactions for each date are added in reverse order in which they are in the app. 

Example:
- QIF file has
  - Day 1:
    - A
    - B
  - Day 2:
    - C
    - D
- Gnucash on the Desktop will show
   - Day 1:
     - B
     - A
   - Day 2:
     - D
     - C

Could this may be fixed by adding a num field to the QIF file. Looking at the QIF spec, such a field is supported and Gnucash shows one, too. Or is there an easier solution I am overlooking?

**Comment by codinguser** [comment]
@fefe982 this falls more in your expertise. Any input?

**Comment by behrmann** [comment]
Well, a nicer solution would actually be for QIF to support a timestamp as well,
unfortunately it does not.

I also don't know, whether it is a bug in Gnucash, that it reads the
transactions in the QIF file in reverse order, but I guess my issue would also
be fixed if the data would be exported reversed, because than gnucash would
import it in the correct order again.

**Comment by behrmann** [comment]
Ok, having looked at this a bit more, I noticed that the ordering in gnucash is no reverse, but basically arbitrary, due to the fact, that the ordering of gnucash for imports is:
"Date Posted, Num, Date Entered, Description, GUID, ..." [[1]](https://lists.gnucash.org/pipermail/gnucash-user/2009-October/031755.html), so all transactions are sorted alphabetically by their Description. 

It would be great if gnucash on Android could keep a rolling (and user-settable) transaction number per account.

**Comment by codinguser** [comment]
So can we close this issue @behrmann ?

**Comment by behrmann** [comment]
Well, not necessarily. Although the bug is with Gnucash in assigning
basically arbitrary order, this could be fixed on this end by providing
a `N` field for a reference number, according to the [QIF
specification](https://web.archive.org/web/20100222214101/http://web.intuit.com/support/quicken/docs/d_qif.html).


I'll try to add one to a QIF file myself and have a look whether Gnucash
imports this correctly.

**Comment by behrmann** [comment]
Well, not necessarily. Although the bug is with Gnucash in assigning basically arbitrary order, this could be fixed on this end by providing a `N` field for a reference number, according to the [QIF
specification](https://web.archive.org/web/20100222214101/http://web.intuit.com/support/quicken/docs/d_qif.html).

I'll try to add one to a QIF file myself and have a look whether Gnucash imports this correctly.

**Comment by codinguser** [comment]
Yes, but that is a different issue altogether. I think reported in #108 
But it would be interesting to know if the N field helps with the GnuCash import
