### ISSUE TITLE
Export Transactions: wrong time suggestion in first export

### ISSUE THREAD

**Issue by alceurneto** [codinguser/gnucash-android#464]
**How to reproduce**
1. Open a new xml file from GnuCash for Android (GCA);
2. Enter some transaction;
3. Select Export from GCA and the suggested time may be wrong (the difference seems to be exactly your time zone):
![2016-01-11 18 12 10](https://cloud.githubusercontent.com/assets/5398143/12242408/11ed2520-b880-11e5-851d-6f25d281c0f7.png)

**Additional information**
- If we select export again, the suggested time seems to be correct;
- I've installed GCA 2.0.5 on my Nexus 5 running Android 6.0.1.

**Comment by codinguser** [comment]
@fefe982 could you verify this bug please?
