### ISSUE TITLE
Accounts: total balance don't show future transactions

### ISSUE THREAD

**Issue by alceurneto** [codinguser/gnucash-android#465]
I'm not sure if it is intentional or not but if we enter a transaction with future date we don't see it in total balance of Accounts screen.
For example, the following account has two transactions one today and other at the end of current month:

**Balance is**
![2016-01-11 18 37 03](https://cloud.githubusercontent.com/assets/5398143/12242681/a69fe5ee-b881-11e5-8713-6e28ee8fc140.png)

**Transactions are**
![2016-01-11 18 36 30](https://cloud.githubusercontent.com/assets/5398143/12242744/f6031ad4-b881-11e5-8eec-86e99c831032.png)

**Additional information**
- I've installed GCA 2.0.5 on my Nexus 5 running Android 6.0.1
- IMHO we could have the same behavior of GnuCash desktop where all transactions are in the balance:
  ![capturar](https://cloud.githubusercontent.com/assets/5398143/12243008/6e10c750-b883-11e5-9e16-37d685adbfc9.PNG)

**Comment by codinguser** [comment]
Thanks for the feedback. Yes this is intentional. 
However, you are right that it may be a good idea to be consistent with GnuCash desktop. 
We will consider it.

**Comment by pfrenssen** [comment]
:+1:
