### ISSUE TITLE
Exported QIF file: we cannot import it in GnuCash desktop

### ISSUE THREAD

**Issue by alceurneto** [codinguser/gnucash-android#466]
**Problem**
I'm trying to import the following QIF files generated in GnuCash Android inside GnuCash desktop but the desktop application exits without messages or warnings and the import is NOT successful.
[can-not-import-desktop.zip](https://github.com/codinguser/gnucash-android/files/86243/can-not-import-desktop.zip)

**Additional information**
- I've installed GCA 2.0.5 on my Nexus 5 running Android 6.0.1;
- I've tested the files in GnuCash Desktop 2.6.10 for Windows and for Mac with the same behavior.

**Comment by halvey** [comment]
I think there is an issue with importing qif's into desktop version 2.6.10 regardless of origin so this may be your problem. Version 2.6.9 and the soon to be released 2.6.11 are good for qif imports apparently.

Cheers Dave H.

**Comment by codinguser** [comment]
Thanks for the update @halvey

**Comment by alceurneto** [comment]
After updated GnuCash Desktop to version 2.6.11 attached files are imported successfully.
