### ISSUE TITLE
Toolbar Icons I'd Love to Have

### ISSUE THREAD

**Issue by pjridge** [codinguser/gnucash-android#468]
1. Delete Split

2. Scheduled Transaction Editor (ie open it)

**Comment by codinguser** [comment]
Could you explain a bit more what you mean? 
There are icons for deleting splits in the split editor and you can edit scheduled transactions as well already.

**Comment by pjridge** [comment]
Hi, Ngewi,

The split editor? What's that? Ah, now I see that when I am in a split, the Delete icon deletes that split. But, of course, it's the same icon as for deleting the whole transaction when I am in an unsplit transaction. Only just now, for the first time did I hold my mouse over the icon and read the pop-up text. Thanks, now OK with that one.

To edit existing scheduled transactions, I have to click Actions, Scheduled Transactions, Scheduled Transaction Editor. Is there a quicker way to open the Scheduled Transaction Editor?

Peter






----- Original Message -----

**Comment by codinguser** [comment]
@pjridge Are you talking about the desktop GnuCash or the Android app?
GnuCash Android only caters to the mobile app

**Comment by pjridge** [comment]
desktop
  ----- Original Message -----

**Comment by pjridge** [comment]
Thanks, Ngewi,

Didn't realise I was in the Android forum.

Peter
  ----- Original Message -----
