### ISSUE TITLE
Exchange rate limited to two decimal places when tranferring between accounts with different currencies

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#474]
The dialog that appears when a transaction transfers money between accounts with different currencies, doesn't allow to enter an exchange rate with more than 2 decimal places.

Reported through User Voice.

**Comment by rivaldi8** [comment]
Fixed in 2.0.6.

**Comment by codinguser** [comment]
No, it's not fixed in v2.0.6. That was already released and propagating to all users. 
It will be released in v2.0.7

**Comment by rivaldi8** [comment]
Oops! Sorry, I didn't notice.

**Comment by codinguser** [comment]
No problemo :)
