### ISSUE TITLE
Scheduled transactions are corrupted after import from .gnucash

### ISSUE THREAD

**Issue by artooy** [codinguser/gnucash-android#482]
I have many scheduled transactions that are working fine on the desktop version. However, after importing to Android, the transactions are not working as defined. If I open transaction split in the Android version one side (the Asset part) of the balance is in the Imbalance account rather than in the correct account where I find 0 instead. This way only the Expense is counted correctly but the Asset part goes to Imbalance always.

**Comment by artooy** [comment]
Sorry, forgot to add some screenshots. I am using GnuCash for Android version 2.0.6

![screenshot_2016-03-08-06-53-48](https://cloud.githubusercontent.com/assets/17709238/13593369/f03a942e-e4fa-11e5-8703-86727c382054.png)

![screenshot_2016-03-08-06-53-34](https://cloud.githubusercontent.com/assets/17709238/13593370/f43295e0-e4fa-11e5-839b-f3156fbd6c3f.png)

![screenshot_2016-03-08-06-53-27](https://cloud.githubusercontent.com/assets/17709238/13593374/f74382c6-e4fa-11e5-9cae-da79d73687e1.png)

**Comment by codinguser** [comment]
Is it possible to send me the file sample which causes this problem? 
You can redact all important information and send only a minimal data which would generate this problem.

**Comment by codinguser** [comment]
Fixed by #563
