### ISSUE TITLE
Feature request: Sort accounts

### ISSUE THREAD

**Issue by superdarrell2** [codinguser/gnucash-android#487]
One of the mainstay of GnuCash's main accounts view is the ability to sort accounts based on name, account code etc. Personally, I used account code to reorder the accounts to my liking.

It would be nice to be able to sort the GnuCash Android accounts so that it'd be more reflective of the account orders users are used to on the desktop.

**Comment by codinguser** [comment]
The accounts are currently sorted by full name.  Or do you mean the short
name?

Also,  what do you mean by account code?

**Comment by codinguser** [comment]
Lacking feedback, I am closing this issue. 
Accounts are currently sorted by name.
