### ISSUE TITLE
owncloud integration

### ISSUE THREAD

**Issue by strk** [codinguser/gnucash-android#497]
It would be useful to have synchronization support to owncloud, in addition to the dropbox/gdrive ones.
See http://www.owncloud.org

**Comment by codinguser** [comment]
Support for ownCloud is already present in the develop branch and will be
released in the future

**Comment by strk** [comment]
Do  you have a commit reference ? Also, when is next release expected ?

**Comment by codinguser** [comment]
8e907f9
No date on the next minor release (which will support ownCloud). 
But patch releases will be coming out often. The next one is in a few days.
