### ISSUE TITLE
Restoring backup from QIF file : Not well-formed

### ISSUE THREAD

**Issue by theindigamer** [codinguser/gnucash-android#515]
I get the error `At line 1, column 0: not well-formed` when importing a backup from a QIF file into GnuCash Android (file was generated using same app but maybe different version).

Sample from QIF file.

```
!Account
NIncome:Gifts Received
^
!Type:Cash
D2016/5/27
MGift from P0
SAssets:Current Assets:Cash in Wallet
$-31.00
^
D2016/5/27
MGift from P1
SAssets:Current Assets:Cash in Wallet
$-25.00
^
```

Also a small suggestion: while exporting to QIF, the user should be told that the timings of the transactions will not be saved.

**Comment by codinguser** [comment]
GnuCash Android does not support importing from QIF

**Comment by theindigamer** [comment]
Oh, okay. Could you please add that as a comment while exporting, maybe as a small alert to the user displayed in orange or red?
