### ISSUE TITLE
file default_accounts.gnucash 

### ISSUE THREAD

**Issue by juandiego26** [codinguser/gnucash-android#523]
hi, 

I new and have a question... for serving the file default_accounts.gnucash  of raw folder

Thanks in advance :)

**Comment by codinguser** [comment]
I'm sorry, I do not quite understand what your question is?

**Comment by juandiego26** [comment]
sorry for not making me understand,

what's it for file **default_accounts.gnucash** located in the folder raw of app

Thanks

**Comment by codinguser** [comment]
This file contains the default accounts which are loaded into the database
if the user requests it.
The user can ask for default accounts immediately after installing the app,
or anytime from `Settings->Accounts`
There are many such files for the different locales (languages) supported
by the app. These files are the same used by GnuCash desktop.

**Comment by juandiego26** [comment]
Thanks  codinguser
