### ISSUE TITLE
If an export through "Sharing" is cancelled, the transaction are still deleted

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#529]
If I try to export, but then change my mind (go back without exporting because I do not see the application I am looking for) all transactions are deleted. I have selected that all transactions should be deleted, but this should happen only if the export is successful.

Steps to reproduce:
1. Add a transaction.
2. Initiate an export, selecting "Share file..." as export destination and checking "Delete transactions after export" option.
3. Press "Export".
4. A system dialog to choose the application will appear. Dismiss it without selecting any application. For example, pressing the phone back button.

The transactions will be deleted but no application will have received the file.

The data is not totally lost, really. It can be restored from the backup in the folder `org.gnucash.android/backups/`. The exported transactions can also be found in the folder `org.gnucash.android/exports/`. These folders should be in the internal storage of the device.

Received through User Voice.

**Comment by codinguser** [comment]
This is an important one. But I can't think of an easy fix, since we do not get feedback from the third-party apps.  
One way would be to make a simple undo button which can be displayed once the user returns to the app. Then we hold restore the last backup. 
But it still feels inelegant and doesn't really solve the problem.

**Comment by rivaldi8** [comment]
Ok, I see. I'll try to think some solution.

**Comment by codinguser** [comment]
It just occurred to me that we always make a backup before exporting. 
I'll add an article to the knowledgebase in UserVoice explaining how to recover data. Users can see those in the Help section. 

Also, if you have any guides or help articles, let me know and we can publish them there too.

**Comment by rivaldi8** [comment]
Yes, I've been thinking about writing some help, but never find the time...

**Comment by codinguser** [comment]
I so know what you mean. 
Same here 😅

**Comment by codinguser** [comment]
I added a help topic explaining how to recover data from backups. 
That should suffice for now
