### ISSUE TITLE
Include whitespace in XML file just like desktop app

### ISSUE THREAD

**Issue by singpolyma** [codinguser/gnucash-android#570]
#### Expected behaviour

Diff of XML export against source file should show differences between the way both apps save data + new transactions usefully.

#### Actual behaviour

Everything in the android export is on a single line, making the diff useless.

**Comment by rivaldi8** [comment]
Already implemented in develop branch (9af8b19). Not sure how well the unmodified parts will be preserved in relation with the desktop version.
