### ISSUE TITLE
app crashes when an account from another book is opened via widget

### ISSUE THREAD

**Issue by nikopp** [codinguser/gnucash-android#574]
#### Expected behaviour
The app should not crash but open the account linked to the widget.

#### Actual behaviour
The app crashes.

#### Steps to reproduce the behaviour
1. Have at least two different books in the app, book 1 and book 2.
2. Open book 1.
3. Create a widget (A) with an account X from book 1.
4. Open book 2. (Not sure if this step is neccessary.)
5. Create a widget (B) with an account Y from book 2.
6. Tap on widget A -> book 1 / account X opens.
7. Tap on widget B -> crash

#### Software specifications
* GnuCash Android version: 2.1.1 beta
* System Android version: 6.0.1
* Device type: Sony Xperia Z3 compact

**Comment by rivaldi8** [comment]
Fixed in ff894a5 (hotfix/patches).

**Comment by riszamohamad4** [comment]
Conflict disparate @nikopp 
![Screenshot_20221013-021944_Bixby Vision](https://github.com/codinguser/gnucash-android/assets/133600642/0a48c253-749b-4cab-8e16-7a4f1bec1ab7)

**Comment by djbrown** [comment]
Hello @riszamohamad4 this project seems abandonned, but a couple of developers have gathered to revive it on a new organisation see https://github.com/codinguser/gnucash-android/issues/913. Could you add more context to your recent comment, what do you mean with "Conflict disparate"?
Maybe we can open an issue on the new repo, may be it will already be resolved within the scope of the revamp.
