### ISSUE TITLE
Latest update won't let us pick the file to open

### ISSUE THREAD

**Issue by singpolyma** [codinguser/gnucash-android#584]
#### Expected behaviour

When hitting "open", be asked what app to use for selecting the file.  Used "Amaze" to allow choosing files from any folder.

#### Actual behaviour

A crippled menu appears that only allows picking files from drive or downloads.

**Comment by codinguser** [comment]
This is a change in functionality which should be documented better, sorry. 
The Open menu only allows access to files which are reachable through the Storage Access Framework. 
In order to access all kinds as before, go through Settings --> Accounts --> Import GnuCash XML
