### ISSUE TITLE
Scheduled exports run with each service run until missed executions are recovered

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#591]
#### Steps to reproduce the behaviour
1. Create a scheduled export.
2. Miss some executions (by turning off the phone, for example).

#### Expected behaviour
The scheduled export isn't executed until the next planned execution.

#### Actual behaviour
The scheduled export is executed every time the ScheduledActionService runs until the missed executions have been done. For example, if two executions have been missed, two exports will be done, then it won't be run again until the next planned date.

#### Software specifications
* GnuCash Android version: 2.1.2
* System Android version: 5.0
* Device type: bq Aquaris E4

**Comment by codinguser** [comment]
Is this still an issue in the current code base in `hotfix/patches`? 
I vaguely remember running into this and fixing it. But I may be wrong

**Comment by rivaldi8** [comment]
I think you refer to #583 which is similar but not the same. There's still another bug related with scheduled action that I'll report shortly.

**Comment by rivaldi8** [comment]
I think you refer to #583 which is similar but not the same. There's still another bug related with scheduled action that I'll report shortly.

**Comment by rivaldi8** [comment]
Fixed in hotfix/patches.
