### ISSUE TITLE
Widget options (display name and whether to show balance)

### ISSUE THREAD

**Issue by czan** [codinguser/gnucash-android#598]
I'm interested in adding some extra options to the widget when it's created. In particular I'm looking at adding:
 - an option to change the text that is displayed on the widget, so we're not forced to use the same string as the account name
 - an option to have a widget that does not display the current balance of the account, so we don't have to worry about people knowing our balances from our home screen

I have already written the code to do this. It's currently on top of the changes done to support books in `hotfix/patches` (which I assumed was the most up-to-date widget code), although I should be able to move it without too much trouble.

I thought it would be worth having a discussion about these options (and whether there are other options people would like to add) before I opened up a pull request, hence opening this issue.

**Comment by codinguser** [comment]
Thanks for the code and for creating this issue so the features can be discussed.

Here are my thoughts on this:
1. What is the benefit of showing some text other than the account name on the widget? This seems like adding complexity with only marginal benefit. Or do you have some use-case in mind? 
@rivaldi8 what do you think?
2. Is the point of a widget with no amount displayed only just to act as a shortcut for opening the account and creating transactions? I see the utility in this. Or is there something else you have in mind?

These are changes which I would rather consider for the `develop` branch.

**Comment by rivaldi8** [comment]
@codinguser I thought the same as you about 1. There should be a really good reason to justify the added complexity.

About 2, I'd like to add something. It would be nice to have the option to show the balance checked by default, unless the user has set a passcode, then it would be unchecked. This would align more with the privacy concerns of the user.

**Comment by codinguser** [comment]
Yes, I like your point about 2. Unchecked by default if passcode is set 👍🏾






On Thu, Oct 13, 2016 at 5:37 PM +0200, "Àlex Magaz Graça" <notifications@github.com> wrote:












@codinguser I thought the same as you about 1. There should be a really good reason to justify the added complexity.



About 2, I'd like to add something. It would be nice to have the option to show the balance checked by default, unless the user has set a passcode, then it would be unchecked. This would align more with the privacy concerns of the user.

**Comment by czan** [comment]
I have two main reasons for 1.

- Similarly to why I think 2 is a good idea, having to use the account name might leak information. I would like my accounts to have meaningful names when I am working with them, but when displayed on the home screen I may want to give it a less meaningful name in order to obscure its meaning to others. (In general, I would consider the widget "public information" and inside the application "private information", and I don't think the two should always be the same.)

- The context of the home-screen is different. Particularly given we lose the account hierarchy, we could have two accounts with the same (or similar) leaf name, but at different points in the hierarchy, which would make them difficult to distinguish on the home screen.

I also don't think there's very much added complexity to the widget.

I'll aim to move my changes onto `develop` over the weekend.

**Comment by codinguser** [comment]
@czan I understand what you mean about obscuring the name, or renaming an account in the hierarchy. The added complexity is not just about the code (although that is one) but also the user experience (and decreasing clutter - feature creep is real). Also, there is the question of cost/benefit.  Code that is written has to be tested, maintained over many years.

As far as I can tell this is not a feature that many users are asking for (and there have been many widget feature requests).. One of the main goals since started GnuCash Android was to keep it as streamlined as possible. This has meant saying no to many good features over the years. 

I'm sorry, but I'm still not convinced that renaming the account in the widget is a feature we should add.  The part about hiding the amount on the widget is a welcome addition though. Looking forward to the pull request.

**Comment by czan** [comment]
I've just made a pull request for the account balance checkbox.

I still disagree with you on the account name issue. I don't think adding an extra text field to the widget creation dialog makes things significantly more complex or cluttered. Creating a widget is not something that is part of a regular workflow: once they are set up the field wouldn't be in the way or be seen.

In the end it's your call, and I doubt I'll be able to change your mind, so I'll just leave it for now.

**Comment by codinguser** [comment]
Fixed in v2.1.3
