### ISSUE TITLE
Widgets stop functioning after changing book

### ISSUE THREAD

**Issue by czan** [codinguser/gnucash-android#607]
#### Steps to reproduce the behaviour
1. Create two books.
2. With `Book 1` active, create a widget looking at any account in `Book 1`
3. Open `Book 2` (making it active), then restart your device
4. Observe that the widget created in step 2 no longer displays the selected account
#### Expected behaviour

The widget continues to display the account it was created with.
#### Actual behaviour

The widget displays "Account name" and one button which does nothing (there are two buttons if this is done on the `develop` branch). Clicking on the widget also does nothing.

If you re-open `Book 1` and restart your device the widget will return to displaying the correct account.
#### My Thoughts

I've taken a look at the code, and the configuration saving/restoring needs to be rewritten. It's currently stored in the `SharedPreferences` for the account's book, but then if/when the widget is updated it tries to read the active book's `SharedPreferences`. We can solve this by either
1. having one big "widget" `SharedPreferences` object, and storing the book as another option for each widget, or
2. we can have a separate `SharedPreferences` object for each widget

I have a slight preference for the second option, but the first is more similar to the current implementation.

**Comment by rivaldi8** [comment]
Unless I'm missing some easy way to get the book associated to a widget, I agree with using the second option. Although I'd rather like to have a widget's preferences stored along with its book, it seems it would unnecessarily complicate the code.

@codinguser What do you think?

**Comment by codinguser** [comment]
@rivaldi8 I'm fine with the second option. The implementation in #608 also looks cleaner than before. 
Thanks @czan .

**Comment by codinguser** [comment]
@rivaldi8 how about we just move this to v2.2.0?
The patch depends on changes already made for hiding balances, etc.

**Comment by rivaldi8** [comment]
@codinguser Ok, moved to 2.2.0.
