### ISSUE TITLE
Timestamp 0 when never exported.

### ISSUE THREAD

**Issue by dannywillems** [codinguser/gnucash-android#615]
#### Steps to reproduce the behaviour
1. Create a new book.
2. Manage books...

#### Expected behaviour
A message like `Never exported`.

#### Actual behaviour
`Last exported: 1970-01-à1 01-00-00.0`

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: 6
* Device type: Phone.

**Comment by rivaldi8** [comment]
Fixed in hotfix/patches.

By the way, I could only reproduce it by going through the first run wizard and choosing to create the account myself. Creating a new book in any other way would always set the current date as last exported.
