### ISSUE TITLE
Hourly backup schedules set as monthly

### ISSUE THREAD

**Issue by schvabodka-man** [codinguser/gnucash-android#625]
#### Steps to reproduce the behaviour
1. Set hourly schedule for importing to cloud
2. Click export
3. It will set to monthly, not the hourly

#### Screenshots
![alt tag](https://locker.ifttt.com/f/f05bc425-265f-466a-bb0f-f95851fb89ec.png)
![alt tag](https://locker.ifttt.com/f/035e2905-0a78-40b3-9d1d-f5f3e4b04713.png)
![alt tag](https://locker.ifttt.com/f/48523c57-23ee-45f8-b6a0-ea7f574bb61b.png)

#### Expected behaviour
Hourly schedule is actually setting to hours

#### Actual behaviour
Hourly schedule is setting to monthly, not the hourly

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: Android 7.0
* Device type: Nexus 5x

**Comment by codinguser** [comment]
@schvabodka-man We do not handle hourly schedules at the moment. But since the dialog is generated through a library, there was no easy way to remove it from the UI. 

We could consider implementing an hourly schedule if there is demand for that. This is the first request I've had on that. 
What do you think @rivaldi8 ?

**Comment by rivaldi8** [comment]
@codinguser I'm not sure. At least now, it seems to me that it would add complexity for little benefit. I'd like to know some use cases for it first. We are also still having issues with scheduled exports and missing other features like specifying multiple weekdays. So again, I'd rather define first what features we want to support to help decide how to deal with the whole thing.

@schvabodka-man why do you need to export hourly?

**Comment by schvabodka-man** [comment]
Because i like to have hourly backups obliviously

**Comment by codinguser** [comment]
@rivaldi8 I agree with you, priority should be on fixing the existing bugs. But we have `HOURLY` in the UI as well. My preference would be to remove it from there and not have to deal with it.

But at the moment, someone could set a schedule for hourly backup and then proceed to delete a book thinking they have a backup, only to find themselves very mistaken. That would be on us.

**Comment by rivaldi8** [comment]
@codinguser Is it even possible to remove the hourly recurrence option from this dialog? There's no documentation and, after a quick look at the code, I can't see how to do so.

**Comment by codinguser** [comment]
I'm not sure that it's possible. I remember looking for it in the docs
once, and also exploring the code a bit.

Unless something has changed in newer versions, no, it's not possible.

**Comment by rivaldi8** [comment]
Then, if it's something we can't workaround easily, I'd try to fix #641, which might make it easier to implement hourly schedules. Otherwise, we'll have to look harder into finding out how to remove the option.

**Comment by codinguser** [comment]
@rivaldi8 so you can go ahead with #641 given the latest roadblock on the Storage Access Framework
