### ISSUE TITLE
App crashes when changing orientation while viewing reports

### ISSUE THREAD

**Issue by diogocp** [codinguser/gnucash-android#633]
#### Steps to reproduce the behaviour
1. Open one of the reports (pie chart, line chart, bar chart or sheet).
2. Turn the phone to change the screen orientation.

#### Expected behaviour
Report shows in the new screen orientation.

#### Actual behaviour
App crashes.

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: Android 6.0.1, CyanogenMod 13.0
* Device type: Nexus 4

**Comment by rivaldi8** [comment]
Confirmed.
