### ISSUE TITLE
BYN currency support not stable

### ISSUE THREAD

**Issue by shrddr** [codinguser/gnucash-android#635]
#### Cases in which it fails

1. Export xml, add a BYN account with desktop gnucash 2.6.13, in gnucash-android open the .gnca file
2. Create default accounts with USD currency, manually create an account with BYN currency in Assets, go to Assets
3. Set default currency to BYN and create default accounts, go to main screen

#### Expected behaviour in each case

1. Import success
2. Show the list of Asset accounts
3. Show parent accounts

#### Actual behaviour in each case

1. Import fails with message "Unsupported ISO 4217 currency code: BYN"
2. Crash
3. Crash immediately, and then at every startup. Have to uninstall

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: 5.0.2
* Device type: Redmi Note 2

**Comment by rivaldi8** [comment]
This currency isn't supported by Java until the latests releases (see [this OpenJDK bug report](https://bugs.openjdk.java.net/browse/JDK-8171296)). It seems it's possible to add new currencies, but only from Java 7 onwards.

One possibility would be to use [Joda-Money](http://www.joda.org/joda-money/). It supports BYN and can be easily extended to support any new currency. It's not API stable yet, so we should check other alternatives first.

By the way, Joda-Money also provides a Money class which we could evaluate to replace ours.

**Comment by codinguser** [comment]
This is can (and probably should) be fixable. We now use our own commodities and if I recall correctly, @rivaldi8 you once did some cleanup to use only our Commodities instead of java Currency. 

Maybe there is some place where Currency is still used. If we change it to commodity, this issue should be fixed. BYN was added to the commodities a while back I think, although I don't recall if only to new installations or also for existing ones. The latter case can easily be fixed with a database migration.

**Comment by codinguser** [comment]
About Joda-Money, well, it is still evolving. If they get to a 1.0 at some point we can evaluate it. 

Although I'm beginning to have increasing inertia to new libraries as we have quite a few already. Build time keeps going up and the apk  is starting to hit the 65k method limit in the develop branch.

**Comment by rivaldi8** [comment]
Ok, I was convinced that `Commodity` worked on top of `Currency` internally. Now I see that's not the case. After quick look at uses of `Currency`, it seems they could be handled by `Commodity`. I'll work then on finishing the migration.

**Comment by codinguser** [comment]
@shrddr @rivaldi8 is this issue fixed in v2.1.5?

**Comment by seriyps** [comment]
@codinguser I have v2.1.5 and it seems that BYN are supported now (at least for importing data from gnucash for desktop)

**Comment by rivaldi8** [comment]
@codinguser The issues reported here seem to be fixed now. There are still a few uses of Currency which may make the application crash, though. I hope to finish the migration to Commodity shortly.

**Comment by codinguser** [comment]
Ok!

**Comment by rivaldi8** [comment]
I've just finished the migration to Commodity.
