### ISSUE TITLE
Weekday is ignored in scheduled exports

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#641]
#### Steps to reproduce the behaviour
1. Go to _Menu > Export..._
2. Set a weekly recurrence with a weekday different of the one for the current date. For example, if today is Monday set it to Thursday.
3. Save changes.

#### Expected behaviour
The export is done weekly on the day set in the recurrence (Thursday in the example).

#### Actual behaviour
The export is done weekly, but on the weekday the scheduled export was created instead (Monday in the example).

The problem is `ScheduledActionService` looks only at the elapsed time since the last export.

#### Software specifications
* GnuCash Android version: 2.1.3

**Comment by codinguser** [comment]
@rivaldi8 Will this issue make it for 2.2.0 release?

**Comment by rivaldi8** [comment]
I think so. I'll work on it this weekend.
