### ISSUE TITLE
android version 7.0 leads to crash ?

### ISSUE THREAD

**Issue by paulle** [codinguser/gnucash-android#642]
#### Steps to reproduce the behaviour
1. Lot of crashes, often when I tried to save a modification.

#### Software specifications
* GnuCash Android version:2.1.3
* System Android version:7.0
* Device type: sony xperia xz

**Comment by paulle** [comment]
This seems to be fixed in v2.1.4

**Comment by codinguser** [comment]
Awesome, then I'll close this issue. 
Feel free to reopen if you notice it again.
