### ISSUE TITLE
Commas in Account name causes error in reporting 

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#649]
#### Steps to reproduce the behaviour
 Inserting a comma character ',' inside an account name messes up the chart display.
Simplified example: Say you have one account with 3 subaccounts: 
Expenses
    |----Ac1
    |----Ac2
    |----Ac3
with transactions in each account.
Then renaming "Ac1" to "Ac1, foo" changes the bar charts contributions. Also, the name for "Ac1, foo" appears just as "Ac1" so my suspicion is that there is some issue with parsing when generating the charts. 

#### Expected behaviour
Bar chart distributions should stay same. 

#### Actual behaviour
Bar chart distributions change
The issue goes away when the comma is remove from the account name.﻿

#### Software specifications
* GnuCash Android version: 2.1.3
* System Android version: 6.0.1 (Cyanogen)
* Device type:

**Comment by pnemonic78** [comment]
Seems to be fixed in version 2.2.0

**Comment by codinguser** [comment]
@pnemonic78 so I can close this issue?

**Comment by pnemonic78** [comment]
Close as non-reproducable

**Comment by codinguser** [comment]
Can't reproduce.
