### ISSUE TITLE
Translation of DropBox to Dropbox

### ISSUE THREAD

**Issue by jony0008** [codinguser/gnucash-android#653]
Please change DropBox to Dropbox in translations.

**Comment by rivaldi8** [comment]
@codinguser Shall we just run `sed` through all strings.xml files or may it mess things up with Crowdin?

**Comment by codinguser** [comment]
@rivaldi8 It could mess things up in CrowdIn. I propose we do the change bit by bit over time. 

@jony0008 do you work for Dropbox? :D  or just particular about spelling ;)

**Comment by jony0008** [comment]
@codinguser Haha No I have just done too many translations :)

**Comment by codinguser** [comment]
Fixed in d566a3e69840e6ab6270233d669ad8e6da6c52ea
