### ISSUE TITLE
Bitcoin currency support

### ISSUE THREAD

**Issue by diogocp** [codinguser/gnucash-android#656]
Please add support for the Bitcoin currency. It does not have an official ISO 4217 currency code yet, but XBT is commonly used.

**Comment by chrisberkhout** [comment]
For inspiration: there's [a patch](https://aur.archlinux.org/cgit/aur.git/tree/xbt.patch?h=gnucash-xbt) I use to do it for GnuCash desktop.
It doesn't add the maximum precision allowed by Bitcoin, but works well enough in practice.

**Comment by rivaldi8** [comment]
@chrisberkhout Thanks for the patch! However, simply adding the currency won't be enough. There's still the problem reported in #635, to be solved by finishing the migration from `Currency` to `Commodity`.

**Comment by rivaldi8** [comment]
Fixed in develop.
