### ISSUE TITLE
Please add Dropbox for "Open" and OneDrive for "export"

### ISSUE THREAD

**Issue by Explorare** [codinguser/gnucash-android#666]
This app can export directly to Dropbox but can't open from it. But for OneDrive is opposite.

**Comment by codinguser** [comment]
Go to Settings -> Accounts --> Import. 
You'll see Dropbox there

**Comment by msvalina** [comment]
Yeah I had the same question, and struggled to find it:
Go to Settings -> Accounts --> Import GnuCash XML --> Hamburger Menu --> Dropbox.
