### ISSUE TITLE
why are liabilities in green

### ISSUE THREAD

**Issue by drjswalker** [codinguser/gnucash-android#675]
#### Steps to reproduce the behaviour
1. Start gnucash
2. Pick expenses:dining as account to operate on.
3. Put in some amount. I used 12.50
4. Select liabilities:credit card as account to withdraw funds from to pay into expenses:dining
5. Finish transaction
6. View accounts. The credit card acount has a green balance of 12.50 and so does the expenses dining. Balance gives $25.

7. Repeat the above with assets:checking instead of the credit card account and assets:checking has a -12.50 entry and bal is zero.

#### Software specifications
* GnuCash Android version:2.1.5
* System Android version: 6.0
* Device type: lg g4

**Comment by codinguser** [comment]
The reason is because Credit card accounts at not considered DEBIT accounts by default (even on Gnucash desktop). 

Look at it this way, the positive value indicates your growing liability by using the credit card. 
When you pay off your credit card, that liability reduces to zero. 

The app shows all positive values as green. On GnuCash desktop, they are just black (but still positive)

**Comment by drjswalker** [comment]
Mmm. I'm a newbie to personal accounting systems, but I think that's a little off for two reasons. To follow the cash flow you need to know up front which account is a debit account and which is a credit account (or have some indicator). For this example, it's pretty obvious. Wouldn't it be simpler to use keep the accounts the same (stateless, neither debit or credit accounts) and use some symbol to indicate a deficit. I seen negative numbers used and parentheses e.g. the Expenses account has 12.50 and the credit card has -12.50 or (12.50) to show money went from the credit card to the expense (which is a sink) either representation  in red. That makes it consistent with the chequing account behaviour which shows a loss of money from the account. It would make the system more intuitive for a non-accountant.  The use of a negative number in red for the credit card account also makes it clear that you're in debt (red = alarm for most western societies) to someone and that's not ok. (I had a similar argument with my bank about a new online app that shows how much credit you have left as a big bold number but the amount you owe them in small print underneath -encouraging people to think that things are ok and you can spend more).  I honestly think that having two types of account (that are not identified as credit or debit accounts up front) and the inconsistency thats associated with it makes things rather confusing. It would be simple to explain that red means debit/debt wherever you are rather than saying green is money you own in debit accounts  (you should know which are debit accounts) and more green is good whereas green is money you owe in credit accounts and more green there is bad. Just a thought

**Comment by codinguser** [comment]
I understand what you mean. But as described in the [GnuCash accounting guide](https://www.gnucash.org/docs/v2.6/C/gnucash-guide/basics-accounting1.html): "Common use of the words debit and credit does not match how accountants use these words. In common use, credit generally has positive associations; in accounting, credit means affecting the right column of the ledger sheet of an account. This is associated with a decrease in asset and expense, but an increase of income, liability and equity accounts." 

Also you could read more here: https://en.wikipedia.org/wiki/Debits_and_credits

GnuCash desktop does allow you to set which accounts are reverse balanced. We do not have that option yet, but we are tracking a request for it at #236. 
For now, we only support the default GnuCash behaviour.

**Comment by codinguser** [comment]
I'll close this issue now. Any developments on this will be tracked in #236
