### ISSUE TITLE
Can't write in the name field when creating a new account

### ISSUE THREAD

**Issue by Jesus-M** [codinguser/gnucash-android#68]
When I try to create a new account, I get the window with empty name field, the default currency /EURO in my case) and the field to pickup a parent account.

If I try to type at account name field nothing happens, but if you first choose a new currency, even if it is the default one, now you can type without problem.

Is it an expected behaviour? 

my envorionment:
App version: 1.1.2
Android version: 2.3.6 (kernel 2.6.38.6-1214151 / compilation GINGERBREAD.XXLK2)
Phone model: Samsung Galaxy Mini 2 (GT-S6500D)

thanks!

**Comment by codinguser** [comment]
@Jesus-M do you still experience this issue in the latest versions?

**Comment by Jesus-M** [comment]
I don't use it since several months ago, sorry

2015-10-27 10:03 GMT+01:00 Ngewi Fet <notifications@github.com>:

**Comment by agalanin** [comment]
Not reproducible for me in 2.0.0.
