### ISSUE TITLE
XML Export of transactions to GDrive generates broken XML since latest version

### ISSUE THREAD

**Issue by m8nky** [codinguser/gnucash-android#686]
#### Steps to reproduce the behaviour
1. Transactions->Export
2. Save As... (file in Google Drive), Format XML
3. Export

4. Open...
5. Choose file from Google Drive
=> 'An error occurred while importing the GnuCash accounts At line 1, column 2: not well-formed (invalid token)'

#### Expected behaviour
Export and Open works, as before the latest update.

#### Actual behaviour
+ The resulting exported XML files seems to be much smaller, than before.
+ Import results in complaints, that the file is invalid:
=> 'An error occurred while importing the GnuCash accounts At line 1, column 2: not well-formed (invalid token)'

#### Software specifications
* GnuCash Android version:2.2.0 (May 3, 2017)
* System Android version: 6.0.1
* Device type: Samsung Galaxy Note 4 (N910FXXS1DQA1)

**Comment by m8nky** [comment]
Hi, please let me share the findings regarding this issue. With version 2.2.1, the XML export is zipped, while the importer expects a plain XML file (uncompressed).

As workaround, until the bug is fixed, one can just unzip the exported file, before importing.

**Comment by codinguser** [comment]
@m8nky Thanks for the report and the workaround. I think I have an idea where to look for the problem.
We will fix this for the next release. Normally, GnuCash Android should open even files which are gzipped.

**Comment by rivaldi8** [comment]
Seems to be fixed in develop branch by c4f6a26..bd8725f.
