### ISSUE TITLE
Sometimes amounts are exported with double minus to QIF

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#693]
#### Steps to reproduce the behaviour
* Create EUR accounts and transactions with an italian android version (keypad for amount only shows commas as decimal separator)
* Export as QIF
* Try to import to GnuCash desktop

#### Expected behaviour
Import process should proceed without problems

#### Actual behaviour
* Import process complains about QIF file format
* Some split transactions have double minus ("--") instead of single minus before the amount

Related to #655 

#### Software specifications
* GnuCash Android version: 2.1.4
* System Android version: 5.1
* Device type: smartphone (moto G 4G - peregrine)

**Comment by rivaldi8** [comment]
Fixed by 2353957 in develop.

@codinguser I'm assuming here, as stated in `Split`'s javadoc, that splits always have positive amounts. However, there are some places where it seems it allows negative amounts ([example](https://github.com/rivaldi8/gnucash-android/blob/54d9149b7d47e145f71912ae72524081ed4f69f4/app/src/main/java/org/gnucash/android/model/Split.java#L89-L89)), which is confusing. If you could confirm that my assumption is right, I'll change all this code to assume positive amounts instead.

**Comment by codinguser** [comment]
@rivaldi8 yes, you are correct in your assumption. 
Splits should always be positive, and the type determines the effect of the split.
