### ISSUE TITLE
Bug: Long list of splits not fully visible

### ISSUE THREAD

**Issue by pnemonic78** [codinguser/gnucash-android#695]
#### Steps to reproduce the behaviour
1. Select existing account
1. Select existing transaction with **many** splits

#### Expected behaviour
Scroll down to see splits

#### Actual behaviour
No scrolling.

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0
* Device type: Samsung Note 4

**Comment by codinguser** [comment]
oops

**Comment by rivaldi8** [comment]
Fixed in hotfix/patches by badbe14.
