### ISSUE TITLE
Zip multiple exported QIF files into one for all export destinations

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#696]
#### Steps to reproduce the behaviour
1. Export transactions with multiple currencies as QIF to ownCloud
2. View files at destination

#### Expected behaviour
3. One zip file containing all exported files

#### Actual behaviour
3. One QIF per currency at destination

#### Software specifications
* GnuCash Android version: all
* System Android version: all
* Device type: all

**Comment by rivaldi8** [comment]
Fixed in develop (c4f6a26).
