### ISSUE TITLE
Transaction details screen footer disappears

### ISSUE THREAD

**Issue by pnemonic78** [codinguser/gnucash-android#699]
#### Steps to reproduce the behaviour
1. Click on existing transaction
1. Click on edit transaction FAB
1. Click on splits icon
1. Add a split
1. Click "save"
1. Click "save" again

#### Expected behaviour
Footer visible.

#### Actual behaviour
Footer removed (balance and date).

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0
* Device type: Any

**Comment by rivaldi8** [comment]
Fixed in hotfix/patches (c18b040).
