### ISSUE TITLE
Split memos disappear

### ISSUE THREAD

**Issue by pnemonic78** [codinguser/gnucash-android#701]
#### Steps to reproduce the behaviour
1. Click on transaction
1. Click on edit FAB button
1. Click on split icon
1. Add memo to 1 or more splits
1. Click "save"
1. Click "save" again
1. Click on edit FAB button
1. Click on split icon

#### Expected behaviour
Splits have their memos.

#### Actual behaviour
Split do not have their memos anymore.

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0
* Device type: Any

**Comment by pnemonic78** [comment]
caused by commit 96a204564147d54ca0b2ec8b393fb5c3aa33c5d1

**Comment by rivaldi8** [comment]
Merged into hotfix/patches (957ae86). Thanks!
