### ISSUE TITLE
Mutual fund, stock, other "XXX currency" assets are not calculated.

### ISSUE THREAD

**Issue by mutedbytes** [codinguser/gnucash-android#716]
#### Steps to reproduce the behaviour
1. Create asset type accounts with underlying stock or mutual fund type accounts.
2. Buy or sell "XXX - no currency" of mutual fund or stock, exchange rate is prompted.
3. Stock or fund asset value is not shown in parent accounts or in each fund or stock account (no $ value or # of shares is shown).

#### Expected behaviour
It should be expected that asset value is calculated and shown at each parent level. The quantity of shares at the fund or stock account level should also be shown.

#### Actual behaviour
$0 and 0# of shares is shown at all account levels.

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0.1
* Device type: LG Nexus 5 phone

**Comment by codinguser** [comment]
Thanks for the bug report @mutedbytes 
Sorry, but the app does not support stock or mutual fund type accounts. 
The account types are only listed there to support importing data from GnuCash desktop without messing it up. But the app doesn't have any support for those account types.
