### ISSUE TITLE
"Buy" and "Sell" appear to be reversed for mutual fund/stock type asset transactions.

### ISSUE THREAD

**Issue by mutedbytes** [codinguser/gnucash-android#717]
#### Steps to reproduce the behaviour
Behavior is produced when creating a transaction under a mutual fund or stock asset type account and using "XXX - no currency" to buy or sell shares.

#### Expected behaviour
When creating a transaction to "buy" stock under a stock defined account, using funds from an income account for example, I would expect the transaction to increase the income account by the purchase amount as well as increase the stock asset account by the same amount. This is the behavior seen in the GnuCash desktop application.

#### Actual behaviour
As it stands, creating a "buy" transaction decreases the stock or mutual fund account, and "sell" increases the asset account, which is opposite of the desktop software and expected accounting behavior.

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0.1
* Device type: LG Nexus 5 phone

**Comment by codinguser** [comment]
Sorry, the app does not support transaction manipulations in stock and mutual fund accounts at this time.
