### ISSUE TITLE
Enhancement :: improvement in input view of transaction

### ISSUE THREAD

**Issue by yohji** [codinguser/gnucash-android#725]
I would to suggest two possibile improvement for the input view of a new transaction:

* a new button for pre-fill the entire amount of the current account (useful for empty the account in favor of another account)

* a way to pre-fill the amount of the transation, as the difference between the current amount of the select account and a calculated *delta*, to reach a desired value (useful for account having a *plafond* like a credit card)

**Comment by yohji** [comment]
I realize that the second one can be solved by just using the operation "-", in conjunction with the total amount of the current account (the first one request). I'm studing the code to implement the first one; I will pull it when/if it is ready. Thanks.

**Comment by codinguser** [comment]
Alright. Remember to read our contribution guidelines: https://github.com/codinguser/gnucash-android/blob/master/.github/CONTRIBUTING.md

**Comment by yohji** [comment]
I propose the #732 pull request in response to this issue. Thanks.

**Comment by codinguser** [comment]
See comment on #732
