### ISSUE TITLE
Asset accounts gets (-) negative sign prepended when editing, causing double negative

### ISSUE THREAD

**Issue by mutedbytes** [codinguser/gnucash-android#726]
#### Steps to reproduce the behaviour
1. Create a transaction to decrease amount in an asset account.
2. Click to edit the transaction, a (-) sign appears in front of red decreasing value
3. Click to save the edited transaction
4. -> error =  the "decrease" transaction now becomes a "negative decrease" resulting in a positive increase to the asset balance

This behavior occurred after changing default transactions to be "credit" rather than "debit" in settings. Not sure if this is relevant.

#### Expected behaviour
Expected behavior would be to have the negative not included in the calculation.

#### Actual behaviour
Negative sign seems to be prepended upon a decrease transaction type. After editing and saving, the negative seems to be included in the resulting calculations, causing the transaction to increase the asset balance rather than decreasing it as should be.

#### Software specifications
* GnuCash Android version: 2.2.1
* System Android version: 6.0.1
* Device type: LG Nexus 5

**Comment by rivaldi8** [comment]
This has already been reported in #723. Please, add any further comments there. Thanks!
