### ISSUE TITLE
 Persian currency symbol is doubled

### ISSUE THREAD

**Issue by hamidrjafari** [codinguser/gnucash-android#731]
#### Steps to reproduce the behaviour
1. Choose IRR as currency symbol

#### Expected behaviour
It should show only one character currency symbol

#### Actual behaviour
It shows two consecutive IRR currency symbols

#### Software specifications
* GnuCash Android version: 2.1.7
* System Android version: 4.2.2
* Device type: Smart phone

Similar bug in the main application and the fix:
[Bug 787479](https://bugzilla.gnome.org/show_bug.cgi?id=787479) - Persian currency symbol is doubled

**Comment by codinguser** [comment]
Thanks for the bug report
