### ISSUE TITLE
Bug:  Incorrect storage of transactions

### ISSUE THREAD

**Issue by DiMan** [codinguser/gnucash-android#743]
Originally, I opened this ticket for an export error of QIF files. After further analysis, I found out that the data in the program is stored incorrectly in some situations. Here is the description of the error. 
(Similar tickets are #723 and #726)

#### Steps to reproduce the behaviour
1. Set "Default Transaction Type" to "CREDIT" (under "Settings" > "Transactions" > "Default Transaction Type")

2. Create new transaction from Account "Assets:Current Assets:Cash in Wallet"
Description = "Test 1" 
Amount = "0.01"
Direction "Spend" (set automatically)
Account  "Expenses:Auto"
3. Save transaction
4. Check the total amount for Account "Cash in Wallet" = -0.01 (🆗)

5. Create new transaction from Account "Assets:Current Assets:Cash in Wallet"
Description = "Test 2" 
Amount = "0.02"
Direction "Spend" (set automatically)
Account  "Assets:Current Assets:Saving Account"
6. Save transaction
7. Now you see two transactions in Account "Cash in Wallet": -0.02€ and -0.01€.

8. Check the total amount for Account "Cash in Wallet" = -0.03€ (🆗)

9. Now change the Account in the transaction "Test 2" 
Change Account: "Assets:Current Assets:Cash in Wallet" => "Expenses:Auto"
10. Save transaction 
11. You still see two transactions in Account "Cash in Wallet": -0.02€ and -0.01€. (🆗)

12. If you check the total amount for Account "Cash in Wallet", you will see **+0.01€**! (✘).

| <img src="https://user-images.githubusercontent.com/426910/32463124-20659614-c33c-11e7-9ef1-8e10e6063917.png" width="250" > | <img src="https://user-images.githubusercontent.com/426910/32463123-1f09c858-c33c-11e7-9895-8c29b17277c5.png" width="250" > |

#### Export transactions to QIF or XML
When exporting the transactions as QIF or XML file, you can see that the data was stored incorrectly:
See row No. 15:
<img src="https://user-images.githubusercontent.com/426910/32463879-58f78ed6-c33e-11e7-9748-3d068c867aa8.png" width="300" >
The transaction was stored with a double minus. See row No. 1495 und 1496. 
<img src="https://user-images.githubusercontent.com/426910/32464364-0facfd36-c340-11e7-9c9f-994f4a732bcc.png" width="600" >

Here are the files: 
[QIF and XML Files.zip](https://github.com/codinguser/gnucash-android/files/1447836/QIF.and.XML.Files.zip)

#### Software specifications
* GnuCash Android version: 2.2.1
* System Android version: 6.0.1 (german)

**Comment by rivaldi8** [comment]
This is the same issue as #723, for which the fix will appear in the next release.
