### ISSUE TITLE
Incorrect sign displayed for credit card account

### ISSUE THREAD

**Issue by MisterY** [codinguser/gnucash-android#748]
Could be related to #723.

#### Steps to reproduce the behaviour
Note that I'm writing from memory.
1. create a credit card account (liability)
2. create the Opening Balance transaction, Decrease, amount 150, from Equity:Opening Balances.

At this point, everything looks OK. The credit card account is 150 in negative.

3. open the same account, edit the transaction.
4. change the amount to 200.
5. go back to Favorite Accounts list.

#### Expected behaviour
The account should now be 200 in debt (Red, -200).

#### Actual behaviour
The account is displayed as 200 in credit. If the terms are confusing, colours are not. :)
The account is now green and has amount +200.

In addition, reversing the transaction by changing the direction to Increase has no effect on the display at the Accounts list. The transaction details, however, are always displayed correctly in the transaction view/edit screens.
The accounts list should display debt in red and with negative values, like in the desktop version.

#### Software specifications
* GnuCash Android version: 2.2.1
* System Android version: 7.1
* Device type: phone

**Comment by MisterY** [comment]
In addition to the above, 

- if I add a €30 charge for Expenses:Dining, there is a transaction that displays both splits as green (credits).
- then I add the same transaction on my Cash account, €10 for Expenses:Dining,
- If I then go to Expenses:Dining account, it displays both transactions green
- On the list of accounts, however, the Dining is green and has a balance of €20.

Fortunately I have a blank database so this is possible to troubleshoot. 
I wonder what the .qif output will be.

Note that this is a book that was created by importing the accounts from the GnuCash export file.

**Comment by codinguser** [comment]
This sounds very close to #723 which is fixed in v2.3.0 beta1. 
Could you please confirm that this issue no longer exists?

**Comment by MisterY** [comment]
OK, here are the findings. v2.3.0-beta2

- Created a transaction in a bank account. The default type was "Receive" so I changed the default tx type to Credit.
- Creating a new transaction in a credit-card account (Liability) shows "Increase" as the direction. 
- Changed that to Decrease and entered a transaction.
- ISSUE: the Favourites list does not display any balances. They are all shown as "XXX0.000000".
- credit card transactions list shows `-xxx25.140000`
- transaction details show two splits:
credit card -25.14
expenses:computer -25.14

**Comment by codinguser** [comment]
I'll close this issue now
