### ISSUE TITLE
Double minus in QIF

### ISSUE THREAD

**Issue by MisterY** [codinguser/gnucash-android#750]
Already mentioned in #743, the exported transactions sometimes contain double minus sign at the Amount.

#### Steps to reproduce the behaviour
1. Created a transaction from a Cash account to Expenses:Dining.
2. Export to QIF.

#### Expected behaviour
The exported file should contain the expense "-10".

#### Actual behaviour
```
!Account
NAssets:Cash Accounts:Cash (EUR)
^
!Type:Cash
D2017/11/13
PFood
M
SExpenses:Dining
$--10.00
```

#### Software specifications
* GnuCash Android version: 2.2.1
* System Android version: 7.0
* Device type: samsung a5

**Comment by rivaldi8** [comment]
Seems cause by the same issue as #723.

**Comment by Maximaximum** [comment]
Seems to be fixed in v.2.3.0

**Comment by rivaldi8** [comment]
Thanks for reporting! Closing...
