### ISSUE TITLE
Feature Request: Starred by Default

### ISSUE THREAD

**Issue by alexandre-mbm** [codinguser/gnucash-android#751]
Setting to open GnuCash app with the Starred tab being showed (actived instead of the All tab).

**Comment by codinguser** [comment]
Thanks for the request. I'm not sure if there is a enough demand for this feature to justify the resources for it. Currently Gnucash Android shows the last tab you opened.

**Comment by codinguser** [comment]
Will close this now. The last opened tab is used when the app loads.
