### ISSUE TITLE
GNUcash always opens previous version of file synced by dropbox

### ISSUE THREAD

**Issue by podabed** [codinguser/gnucash-android#770]
#### Steps to reproduce the behaviour
1. Use *.gnucash in dropbox between pc and phone.
2. Android gnucash always opens previous version of file instead of last version already synced by dropbox. PC version always open last version.

#### Expected behaviour
Like in PC. Always opens last version.

#### Actual behaviour
Opens previous version.

#### Software specifications
* GnuCash Android version:2.3.0
* System Android version:7.1.2
* Device type:Phone

**Comment by codinguser** [comment]
This is essentially synchronization. I'll merge this into the existing sync request #737
