### ISSUE TITLE
Where can I change the title "review" to my language?

### ISSUE THREAD

**Issue by pablopy** [codinguser/gnucash-android#778]
I would like to know where I could modify the word review to my language in Spanish because I can not find it in the file es\ strings.xml.
I would also like to change the currency from the local currency of my default u $$ to the local currency of my country.

**Comment by rivaldi8** [comment]
Translation are done through [Crowdin](https://crowdin.com/project/gnucash-android).

You can change the currency in _Settings > Accounts > Default Currency_ (_Ajustes > Cuentas > Divisa por defecto_).
