### ISSUE TITLE
Default edit action as floating action button (FAB)

### ISSUE THREAD

**Issue by pnemonic78** [codinguser/gnucash-android#783]
Many screens have "+" floating action button (FAB) for the main action, but the transaction overview screen does not.

#### Steps to reproduce the behaviour
1. Click into account screen
2. Click into existing transaction screen

#### Expected behaviour
"Edit" button as FAB in bottom-right

#### Actual behaviour
"Edit" button in top-left

**Comment by codinguser** [comment]
Thanks for the suggestion. Why would it be better to have the button at the bottom?

**Comment by pnemonic78** [comment]
I can even volunteer to do the change - just need the approval.

**Comment by codinguser** [comment]
@pnemonic78  
The Material design guide does say that the FAB represents the primary action of a screen. But the edit action is not really the primary action of the transaction detail screen. And that is my issue with moving it down and making it bigger. 

The transaction detail screen is meant for just viewing the transaction details, and you happen to have the possibility to edit. But editing is not the primary action you are expected to perform when you get there. Moving the button down gives it prominent placement which would suggest that.

Also, if you look at the [Placement section](https://material.io/design/components/buttons-floating-action-button.html#placement) of the FAB design page, you can see that the FAB can also be attached to "top app bars and the edge of some components."
