### ISSUE TITLE
XXX Unknown Currency when importing accounts from GNUCash desktop

### ISSUE THREAD

**Issue by rjack** [codinguser/gnucash-android#787]
#### Steps to reproduce the behaviour

1. from GNUCash desktop, export accounts
2. from gnucash-android, import GNUCash XML

#### Expected behaviour

Currency for all imported accounts should be the same as te currency in the original (i.e. desktop) accounts configuration; it should be consistent with the default currency setting in the gnucash-android app.

#### Actual behaviour

All accounts have XXX Unknown currency.
Manually adjusting currency setting for all accounts is a pain, there is no way to propagate the change to all subaccounts.

#### Software specifications
* GnuCash Android version: 2.3.1
* System Android version: Android 7,0
* Device type: Galaxy A5 2016

**Comment by codinguser** [comment]
Duplicate #764 which is fixed in `develop` branch and in 2.4.0-beta1
