### ISSUE TITLE
Export to csv - App breaks down

### ISSUE THREAD

**Issue by rainerfeldbruegge** [codinguser/gnucash-android#809]
#### Steps to reproduce the behaviour
1. Pick Menu Export, 
 export to file/owncloud/mail (same behaviour for all)
 format csv
time from 01.01.2019
delete transactions after export: no
repeat: none

Tip "Exportieren"

#### Expected behaviour
A file is created in csv-format

#### Actual behaviour
gnu-cash breaks down, Application halted
no file created.
whenn i pick export to "speichern unter" there is a file created, but empty.

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 6.0.1
* Device type: FP 2 (FairPhone)

**Comment by jainharsh96** [comment]
I am working on this issue.

**Comment by jainharsh96** [comment]
I resolved the issue
