### ISSUE TITLE
Add button in schedule action disappears after rotation

### ISSUE THREAD

**Issue by shabrikaruna** [codinguser/gnucash-android#811]
Steps to reproduce the behavior

1. Open navigation drawer
2. Click on schedule actions
3. Go to exports
4. Rotate the device

Expected behavior
The button should not disappear

Actual behavior
The button not appearing after rotation

**Comment by RajatChandel** [comment]
I will look into it

**Comment by RajatChandel** [comment]
I resolved this issue, after rotation it was taking the default value in actionType ie. transaction action.

**Comment by codinguser** [comment]
Will be fixed in next release
