### ISSUE TITLE
"No transactions found" when try to export all transactions

### ISSUE THREAD

**Issue by emakei** [codinguser/gnucash-android#840]
#### Steps to reproduce the behaviour
1. Enable "Export all transactions" in settings
2. Export all transactions (any method)

#### Expected behaviour
All transactions are exported

#### Actual behaviour
I see "No transactions found"

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 9
* Device type: Samsung Galaxy A50 SM-A505FM/DS

**Comment by nottheend** [comment]
I can also confirm with same android

**Comment by d687r02j8g** [comment]
I also have this issue.

**Comment by d687r02j8g** [comment]
On the latest beta version I get an error saying

Error exporting CSVT
Division by zero

**Comment by demonfiddler** [comment]
On the same Android & GnuCash versions, I'm seeing similar problems exporting CSV or QIF with Save As... (file on SD card) / All time options selected **without** the 'Delete transactions after export' option: the file gets created but it is empty. See also #819.
