### ISSUE TITLE
Migrating whole book to new android instance

### ISSUE THREAD

**Issue by nodje** [codinguser/gnucash-android#842]
I find myself unable to migrate my Gnucash accounts & transactions to a new android instance.
Is there a way to do this easily?

I tried copying all Backups and book files and put them in the new profile on the new device but it wouldn't work.

**Comment by arozaqf** [comment]
Export to xml and open the exported file to new device

**Comment by nodje** [comment]
Works, thanks.
Had a problem with duplicate ROOT account. Had three of them in my exported XML for some reasons.
