### ISSUE TITLE
Close Main Navigation Menu with Back button

### ISSUE THREAD

**Issue by JeanGarf** [codinguser/gnucash-android#857]
#### Steps to reproduce the behaviour
1. Click on the "home" button to open Main Navigation Menu
2. Click back button

3. Open "General Preferences"
4. Click back button

#### Expected behaviour
2. The Main Navigation Menu should close

4. "General Preferences" are closing and return to Preference List

#### Actual behaviour
2. GnuCashAndroid is closed

4. "General Preferences" closes and returns to Account Activity

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 9.0
* Device type: Samsung Galaxy Note 8

**Comment by JeanGarf** [comment]
I'have corrected this issue in eb38f2e60ef3966fb172c438d9fde345210e6106, but I don't know yet how to give it to you

**Comment by codinguser** [comment]
thanks @JeanGarf
