### ISSUE TITLE
Use ₽ sign to designate Russian ruble, instead of "руб"

### ISSUE THREAD

**Issue by lompy** [codinguser/gnucash-android#861]
Issue from the [forum thread](https://gnucash.uservoice.com/forums/320493-gnucash-android/suggestions/32571610-use-sign-to-designate-russian-ruble-instead-of)

> It is incorrect to use "руб" as a prefix for the amount of money. One can either write "₽500" or "500 руб." (with white space and dot). For this application I recommend to use the first one.

**Comment by lompy** [comment]
Also the last letter of the "руб" tends to be interpreted as the first digit "6" of the number: "руб105.91". Highly unreadable.

**Comment by codinguser** [comment]
develop branch already has the symbol ₽

**Comment by codinguser** [comment]
Will be available in next release
