### ISSUE TITLE
Let's combine forces on gnucash-android

### ISSUE THREAD

**Issue by djbrown** [codinguser/gnucash-android#917]
Hello @reul,

today I saw that you had recently merged some pull requests on this previsouly presumed abandonned repo: #915 #916
Do you have enough rights to administer/maintain this repo?

Over the last year many people inclding me have tried to revive the project but under the main issue #913 (Let's help the project go go on!) we couldn't find anyone with write access to the repo.
So we created the fork under [GnuCash-Pocket](https://github.com/GnuCash-Pocket/gnucash-android) and updated all the dependencies etc. I also added build and test pipelines that run on each pull request, fully transparent but also securely.

But some tests kept failing so I never felt confident to create a release.
Back when I tried to gather tracktion, I even tried to coordinate with the GnuCash Devs, but as of now they said the project should be kept seperately from main the desktop project.

Can we merge in the improvements (at least the new pipelines) and continue the project under this original repo under the current owner codinguser or even on an organization?

Kind Gerards
Daniel

**Comment by reul** [comment]
Hey! Actually I was trying to send a PR to my own fork and a couple of times I just automatically followed github defaults and sent those to the main repo. Then I just closed those because they were not production ready yet.

**Comment by reul** [comment]
I don't see any activity under @codinguser account and his website/domain is now dead. I don't know what happened but this account is abandoned.

I am very much interested in keeping the project alive and modernizing it.

**Comment by djbrown** [comment]
Ah yes, I overlooked your pull requests weren't actually merged in, but only closed.
But thanks for already posting a pull request to the new repo https://github.com/GnuCash-Pocket/gnucash-android/pull/22. I already had a look on that ❤

Anyone else interested in helping out, please reach out ;-)
Currently the overall project plan is still on https://github.com/GnuCash-Pocket/gnucash-android/issues/8
That may be moved to a proper GitHub Project, once the most important tasks are done.
